// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ActividadePlano
    {
        [StringLength(50)]
        public string IdActividadePlano { get; set; }
        [StringLength(50)]
        public string ActividadeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }

        [ForeignKey("ActividadeId")]
        [InverseProperty("ActividadePlano")]
        public virtual Actividade Actividade { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("ActividadePlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}