// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class AgravamentoAcidentesTrabalho
    {
        [StringLength(50)]
        public string IdAgravamentoAcidentesTrabalho { get; set; }
        public double? TaxaAgravamento { get; set; }
        [StringLength(50)]
        public string TaxaSinistralidadeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        public bool? IsTaxa { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("AgravamentoAcidentesTrabalho")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("TaxaSinistralidadeId")]
        [InverseProperty("AgravamentoAcidentesTrabalho")]
        public virtual TaxaSinistralidade TaxaSinistralidade { get; set; }
    }
}