// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class AgravamentoDespesa
    {
        [StringLength(50)]
        public string IdAgravamentoDespesa { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string AgravamentoId { get; set; }
        [StringLength(50)]
        public string DespesaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [ForeignKey("AgravamentoId")]
        [InverseProperty("AgravamentoDespesa")]
        public virtual Agravamento Agravamento { get; set; }
        [ForeignKey("DespesaId")]
        [InverseProperty("AgravamentoDespesa")]
        public virtual Despesa Despesa { get; set; }
    }
}