// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class AjudaCampoTabela
    {
        [StringLength(50)]
        public string Id { get; set; }
        [StringLength(150)]
        public string NomeTabela { get; set; }
        [StringLength(150)]
        public string NomeCampo { get; set; }
        [StringLength(1000)]
        public string Ajuda { get; set; }
        [StringLength(10)]
        public string CodAjudaCampoTabela { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("AjudaCampoTabela")]
        public virtual Estado Estado { get; set; }
    }
}