// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class AnexosAutomovel
    {
        [StringLength(50)]
        public string IdAnexosAutomovel { get; set; }
        [StringLength(500)]
        public string Designacao { get; set; }
        [StringLength(800)]
        public string CaminhoFicheiro { get; set; }
        [StringLength(50)]
        public string AutomovelId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("AutomovelId")]
        [InverseProperty("AnexosAutomovel")]
        public virtual Automovel Automovel { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("AnexosAutomovel")]
        public virtual Estado Estado { get; set; }
    }
}