// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Assinantes
    {
        public Assinantes()
        {
            ContratadosAssinantes = new HashSet<ContratadosAssinantes>();
            ContratantesAssinantes = new HashSet<ContratantesAssinantes>();
        }

        [StringLength(50)]
        public string IdAssinante { get; set; }
        [StringLength(50)]
        public string CodAssinante { get; set; }
        [StringLength(50)]
        public string AssinanteId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [ForeignKey("AssinanteId")]
        [InverseProperty("Assinantes")]
        public virtual Pessoa Assinante { get; set; }
        [InverseProperty("Assinante")]
        public virtual ICollection<ContratadosAssinantes> ContratadosAssinantes { get; set; }
        [InverseProperty("Assinante")]
        public virtual ICollection<ContratantesAssinantes> ContratantesAssinantes { get; set; }
    }
}