// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Beneficiario
    {
        [StringLength(50)]
        public string IdBeneficiario { get; set; }
        [Column("PessoaID")]
        [StringLength(50)]
        public string PessoaId { get; set; }
        [Column("GrauParentescoID")]
        [StringLength(50)]
        public string GrauParentescoId { get; set; }
        [Column("CotacaoID")]
        [StringLength(50)]
        public string CotacaoId { get; set; }
        [StringLength(2000)]
        public string Obs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string ApoliceId { get; set; }

        [ForeignKey("ApoliceId")]
        [InverseProperty("Beneficiario")]
        public virtual Apolice Apolice { get; set; }
        [ForeignKey("CotacaoId")]
        [InverseProperty("Beneficiario")]
        public virtual Cotacao Cotacao { get; set; }
        [ForeignKey("GrauParentescoId")]
        [InverseProperty("Beneficiario")]
        public virtual GrauParentesco GrauParentesco { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("Beneficiario")]
        public virtual Pessoa Pessoa { get; set; }
    }
}