// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Bonus
    {
        [StringLength(50)]
        public string IdBonus { get; set; }
        public double TaxaBonus { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime DataFim { get; set; }
        [Required]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Required]
        [Column("PlanoProdutoID")]
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        public double ValorMinPremioSimples { get; set; }
        public double ValorMaxPremioSimples { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public double ValorMinBonus { get; set; }
        public double ValorMaxBonus { get; set; }
        [Required]
        public bool? IsTaxa { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [Column("MoedaID")]
        [StringLength(50)]
        public string MoedaId { get; set; }
        [StringLength(50)]
        public string CanalId { get; set; }
        [StringLength(50)]
        public string CentroCustoId { get; set; }
        [StringLength(50)]
        public string TipoRecebimentoId { get; set; }
        [StringLength(50)]
        public string ProdutorId { get; set; }
        [StringLength(50)]
        public string CodBonus { get; set; }
        [StringLength(50)]
        public string TipoOperacaoId { get; set; }

        [ForeignKey("CanalId")]
        [InverseProperty("Bonus")]
        public virtual Canal Canal { get; set; }
        [ForeignKey("CentroCustoId")]
        [InverseProperty("Bonus")]
        public virtual CentroCusto CentroCusto { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Bonus")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("Bonus")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("Bonus")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("ProdutorId")]
        [InverseProperty("Bonus")]
        public virtual Pessoa Produtor { get; set; }
        [ForeignKey("TipoOperacaoId")]
        [InverseProperty("Bonus")]
        public virtual TipoOperacao TipoOperacao { get; set; }
        [ForeignKey("TipoRecebimentoId")]
        [InverseProperty("Bonus")]
        public virtual TipoRecebimento TipoRecebimento { get; set; }
    }
}