// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CaePlano
    {
        [StringLength(50)]
        public string IdCaePlano { get; set; }
        [StringLength(50)]
        public string CaeId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string CodCaePlano { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("CaeId")]
        [InverseProperty("CaePlano")]
        public virtual Cae Cae { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("CaePlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("CaePlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}