// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CanalContratos
    {
        [StringLength(50)]
        public string IdCanalContratos { get; set; }
        [StringLength(50)]
        public string ContratoId { get; set; }
        [StringLength(50)]
        public string CodCanalContratos { get; set; }
        [StringLength(50)]
        public string CanalContratoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [ForeignKey("CanalContratoId")]
        [InverseProperty("CanalContratos")]
        public virtual Canal CanalContrato { get; set; }
        [ForeignKey("ContratoId")]
        [InverseProperty("CanalContratos")]
        public virtual Contrato Contrato { get; set; }
    }
}