// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CanalMenu
    {
        [StringLength(50)]
        public string IdCanalMenu { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string CodCanalMenu { get; set; }
        [StringLength(50)]
        public string CanalId { get; set; }
        [StringLength(50)]
        public string MenuId { get; set; }
        [StringLength(50)]
        public string SubMenuId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [ForeignKey("CanalId")]
        [InverseProperty("CanalMenu")]
        public virtual Canal Canal { get; set; }
        [ForeignKey("MenuId")]
        [InverseProperty("CanalMenu")]
        public virtual Menu Menu { get; set; }
        [ForeignKey("SubMenuId")]
        [InverseProperty("CanalMenu")]
        public virtual SubMenu SubMenu { get; set; }
    }
}