// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CanaisComissionamento
    {
        [StringLength(50)]
        public string IdCanaisComissionamento { get; set; }
        [StringLength(50)]
        public string CanalId { get; set; }
        [StringLength(50)]
        public string CodCanaisComissionamento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string ComissionamentoId { get; set; }

        [ForeignKey("ComissionamentoId")]
        [InverseProperty("CanaisComissionamento")]
        public virtual Comissionamento Comissionamento { get; set; }
    }
}