// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Capitulo
    {
        public Capitulo()
        {
            Artigo = new HashSet<Artigo>();
        }

        [StringLength(50)]
        public string IdCapitulo { get; set; }
        [StringLength(2048)]
        public string Designacao { get; set; }
        [Column("CondicoesID")]
        [StringLength(50)]
        public string CondicoesId { get; set; }
        [Column("OBS")]
        [StringLength(2048)]
        public string Obs { get; set; }
        [StringLength(10)]
        public string CodCapitulo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [StringLength(50)]
        public string NumCapitulo { get; set; }

        [ForeignKey("CondicoesId")]
        [InverseProperty("Capitulo")]
        public virtual Condicoes Condicoes { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Capitulo")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("Capitulo")]
        public virtual ICollection<Artigo> Artigo { get; set; }
    }
}