// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CaracteristicaClassificacao
    {
        public CaracteristicaClassificacao()
        {
            CaracteristicaObjecto = new HashSet<CaracteristicaObjecto>();
            InverseSuperCaracteristica = new HashSet<CaracteristicaClassificacao>();
            ValorPadrao = new HashSet<ValorPadrao>();
        }

        [StringLength(50)]
        public string IdCaracteristicaClassificacao { get; set; }
        [StringLength(100)]
        public string Descricao { get; set; }
        [StringLength(50)]
        public string ClassificacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string SuperCaracteristicaId { get; set; }

        [ForeignKey("ClassificacaoId")]
        [InverseProperty("CaracteristicaClassificacao")]
        public virtual Classificacao Classificacao { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("CaracteristicaClassificacao")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("SuperCaracteristicaId")]
        [InverseProperty("InverseSuperCaracteristica")]
        public virtual CaracteristicaClassificacao SuperCaracteristica { get; set; }
        [InverseProperty("CaracteristicaClassificacao")]
        public virtual ICollection<CaracteristicaObjecto> CaracteristicaObjecto { get; set; }
        [InverseProperty("SuperCaracteristica")]
        public virtual ICollection<CaracteristicaClassificacao> InverseSuperCaracteristica { get; set; }
        [InverseProperty("Caracteristica")]
        public virtual ICollection<ValorPadrao> ValorPadrao { get; set; }
    }
}