// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ChefeSeccao
    {
        [StringLength(50)]
        public string IdChefeSeccao { get; set; }
        [Column("SeccaoID")]
        [StringLength(50)]
        public string SeccaoId { get; set; }
        [Column("ChefeID")]
        [StringLength(50)]
        public string ChefeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("ChefeId")]
        [InverseProperty("ChefeSeccao")]
        public virtual Funcionario Chefe { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("ChefeSeccao")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("SeccaoId")]
        [InverseProperty("ChefeSeccao")]
        public virtual Seccao Seccao { get; set; }
    }
}