// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CircunstanciaPerda
    {
        public CircunstanciaPerda()
        {
            Perda = new HashSet<Perda>();
        }

        [StringLength(50)]
        public string IdCircunstanciaPerda { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodCircunstanciaPerda { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("CircunstanciaPerda")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("CircunstanciaPerda")]
        public virtual ICollection<Perda> Perda { get; set; }
    }
}