// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ClassificacaoEntidade
    {
        public ClassificacaoEntidade()
        {
            Banco = new HashSet<Banco>();
            EntidadeEmpregadora = new HashSet<EntidadeEmpregadora>();
        }

        [StringLength(50)]
        public string IdClassificacaoEntidade { get; set; }
        [StringLength(300)]
        public string Designacao { get; set; }
        [Column("TipoEntidadeID")]
        [StringLength(50)]
        public string TipoEntidadeId { get; set; }
        [StringLength(10)]
        public string CodClassificacaoEntidade { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ClassificacaoEntidade")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("TipoEntidadeId")]
        [InverseProperty("ClassificacaoEntidade")]
        public virtual TipoEntidade TipoEntidade { get; set; }
        [InverseProperty("ClassificacaoEntidade")]
        public virtual ICollection<Banco> Banco { get; set; }
        [InverseProperty("ClassificacaoEntidade")]
        public virtual ICollection<EntidadeEmpregadora> EntidadeEmpregadora { get; set; }
    }
}