// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ClassificacaoCaixa
    {
        public ClassificacaoCaixa()
        {
            Caixa = new HashSet<Caixa>();
        }

        [StringLength(50)]
        public string IdClassificacaoCaixa { get; set; }
        [StringLength(10)]
        public string CodClassificacaoCaixa { get; set; }
        [StringLength(200)]
        public string Designacao { get; set; }
        [Column("SubContaID")]
        [StringLength(50)]
        public string SubContaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        [StringLength(50)]
        public string BancoId { get; set; }
        [StringLength(50)]
        public string InformacaoBancariaId { get; set; }

        [ForeignKey("BancoId")]
        [InverseProperty("ClassificacaoCaixa")]
        public virtual Banco Banco { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("ClassificacaoCaixa")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("InformacaoBancariaId")]
        [InverseProperty("ClassificacaoCaixa")]
        public virtual InformacaoBancaria InformacaoBancaria { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("ClassificacaoCaixa")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("SubContaId")]
        [InverseProperty("ClassificacaoCaixa")]
        public virtual PlanoContas SubConta { get; set; }
        [InverseProperty("ClassificacaoCaixa")]
        public virtual ICollection<Caixa> Caixa { get; set; }
    }
}