// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ClasseRisco
    {
        public ClasseRisco()
        {
            Tarifa = new HashSet<Tarifa>();
        }

        [StringLength(50)]
        public string IdClasseRisco { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        public double? Acrescimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column(TypeName = "ntext")]
        public string Descricao { get; set; }
        [StringLength(50)]
        public string CodClasseRisco { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ClasseRisco")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("ClasseRisco")]
        public virtual ICollection<Tarifa> Tarifa { get; set; }
    }
}