// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ClassificacaoReclamacao
    {
        public ClassificacaoReclamacao()
        {
            Reclamacao = new HashSet<Reclamacao>();
        }

        [StringLength(50)]
        public string IdClassificacaoReclamacao { get; set; }
        [StringLength(204)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodClassificacaoReclamacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ClassificacaoReclamacao")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("ClassificacaoReclamacao")]
        public virtual ICollection<Reclamacao> Reclamacao { get; set; }
    }
}