// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ClasseModalidadeSeguro
    {
        public ClasseModalidadeSeguro()
        {
            SubClasseModalidadeSeguro = new HashSet<SubClasseModalidadeSeguro>();
        }

        [StringLength(50)]
        public string IdClasseModalidadeSeguro { get; set; }
        [StringLength(50)]
        public string CodClasseModalidadeSeguro { get; set; }
        [Column(TypeName = "ntext")]
        public string Descricao { get; set; }
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ClasseModalidadeSeguro")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("ClasseModalidadeSeguro")]
        public virtual Produto Produto { get; set; }
        [InverseProperty("ClasseModalidadeSeguro")]
        public virtual ICollection<SubClasseModalidadeSeguro> SubClasseModalidadeSeguro { get; set; }
    }
}