// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ClassificacaoGrupo
    {
        public ClassificacaoGrupo()
        {
            Cotacao = new HashSet<Cotacao>();
            TipoClassificacaoGrupo = new HashSet<TipoClassificacaoGrupo>();
        }

        [StringLength(50)]
        public string IdClassificacaoGrupo { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Datatualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodClassificacaoGrupo { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ClassificacaoGrupo")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("ClassificacaoGrupo")]
        public virtual ICollection<Cotacao> Cotacao { get; set; }
        [InverseProperty("ClassificacaoGrupo")]
        public virtual ICollection<TipoClassificacaoGrupo> TipoClassificacaoGrupo { get; set; }
    }
}