// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CoberturaPlano
    {
        public CoberturaPlano()
        {
            CoberturaSelecionada = new HashSet<CoberturaSelecionada>();
            PremiosCoberturaAcidentesPessoais = new HashSet<PremiosCoberturaAcidentesPessoais>();
        }

        [StringLength(50)]
        public string IdCoberturaPlano { get; set; }
        public double? PorAnuidade { get; set; }
        public double? PorCadaSinistro { get; set; }
        public double? PorCadaPessoaSinistrada { get; set; }
        public double? PorDanosCoisasAnimais { get; set; }
        public bool? Personalizado { get; set; }
        public double? ValorPersonalizado { get; set; }
        public double? CoPagamento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("PlanoProdutoID")]
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string CoberturaId { get; set; }
        public bool? IsComplementar { get; set; }
        public double? Preco { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        [StringLength(500)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string Nota { get; set; }
        public double? TaxaCobertura { get; set; }
        [StringLength(500)]
        public string Descricao { get; set; }
        [StringLength(50)]
        public string NivelRiscoId { get; set; }
        public double? PorCada { get; set; }
        public bool? IsPadrao { get; set; }
        public bool? IsPrincipal { get; set; }

        [ForeignKey("CoberturaId")]
        [InverseProperty("CoberturaPlano")]
        public virtual Cobertura Cobertura { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("CoberturaPlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("CoberturaPlano")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("NivelRiscoId")]
        [InverseProperty("CoberturaPlano")]
        public virtual NivelRisco NivelRisco { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("CoberturaPlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [InverseProperty("CoberturaPlano")]
        public virtual ICollection<CoberturaSelecionada> CoberturaSelecionada { get; set; }
        [InverseProperty("CoberturaPlano")]
        public virtual ICollection<PremiosCoberturaAcidentesPessoais> PremiosCoberturaAcidentesPessoais { get; set; }
    }
}