// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Cobertura
    {
        public Cobertura()
        {
            BeneficioCobertura = new HashSet<BeneficioCobertura>();
            CoberturaCosseguro = new HashSet<CoberturaCosseguro>();
            CoberturaPlano = new HashSet<CoberturaPlano>();
            CoberturaResseguro = new HashSet<CoberturaResseguro>();
            Despesa = new HashSet<Despesa>();
            DespesaPlano = new HashSet<DespesaPlano>();
            DocumentosCoberturas = new HashSet<DocumentosCoberturas>();
            ExclusoesCobertura = new HashSet<ExclusoesCobertura>();
            GarantiasCobertura = new HashSet<GarantiasCobertura>();
            LimiteCobertura = new HashSet<LimiteCobertura>();
            NivelRiscoCobertura = new HashSet<NivelRiscoCobertura>();
            RiscosExcluidos = new HashSet<RiscosExcluidos>();
            ServicosAdicionais = new HashSet<ServicosAdicionais>();
            ServicosBase = new HashSet<ServicosBase>();
            SobrePremioCoberturaAdicionalCobertura = new HashSet<SobrePremioCoberturaAdicional>();
            SobrePremioCoberturaAdicionalCoberturaAdicional = new HashSet<SobrePremioCoberturaAdicional>();
        }

        [StringLength(50)]
        public string IdCobertura { get; set; }
        [StringLength(2048)]
        public string DescricaoCobertura { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataEfectividadeCobertura { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataTerminoCobertura { get; set; }
        public double? ValorMin { get; set; }
        public double? ValorMax { get; set; }
        public double? CooPagamentoMin { get; set; }
        public double? CooPagamentoMax { get; set; }
        public double TaxaCooPagamento { get; set; }
        public bool? CoberturaAdicional { get; set; }
        public bool? CoberturaRenovavel { get; set; }
        public bool? CustoCoberturaQualificado { get; set; }
        public int? NumReivindicacoesPermitidas { get; set; }
        public bool? CoberturaSujeitaCoSeguro { get; set; }
        public bool? CoberturaDeveEstarRenovacao { get; set; }
        public bool? CoberturaSolicitada { get; set; }
        public bool? ForneceValorResgateEmDinheiro { get; set; }
        public bool? SubContratentesCobertos { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        public double? PercentagemDentroRede { get; set; }
        public double? PercentagemForaRede { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        [StringLength(10)]
        public string CodCoberturaProduto { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(4000)]
        public string Obs { get; set; }
        public double? LimiteIndemnizacao { get; set; }
        [Required]
        public bool? IsTaxa { get; set; }
        [Column("SubContaID")]
        [StringLength(50)]
        public string SubContaId { get; set; }
        [Column("NaturezaMovimentoID")]
        [StringLength(50)]
        public string NaturezaMovimentoId { get; set; }
        [Required]
        public bool? Contabiliza { get; set; }
        public bool? IsPadrao { get; set; }
        [Column("LinhaProdutoID")]
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [StringLength(50)]
        public string CodDesconto { get; set; }
        [StringLength(50)]
        public string FranquiaId { get; set; }
        public double? Capital { get; set; }
        public double? PercentagemMinimaForaRede { get; set; }
        public double? PercentagemMaximaForaRede { get; set; }
        [StringLength(50)]
        public string TipoCoberturaId { get; set; }
        [StringLength(50)]
        public string FormaReparacaoId { get; set; }
        public bool? Selecionavel { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("Cobertura")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FormaReparacaoId")]
        [InverseProperty("Cobertura")]
        public virtual FormaReparacao FormaReparacao { get; set; }
        [ForeignKey("FranquiaId")]
        [InverseProperty("Cobertura")]
        public virtual Franquia Franquia { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("Cobertura")]
        public virtual LinhaProduto LinhaProduto { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("Cobertura")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("NaturezaMovimentoId")]
        [InverseProperty("Cobertura")]
        public virtual NaturezaMovimento NaturezaMovimento { get; set; }
        [ForeignKey("SubContaId")]
        [InverseProperty("Cobertura")]
        public virtual PlanoContas SubConta { get; set; }
        [ForeignKey("TipoCoberturaId")]
        [InverseProperty("Cobertura")]
        public virtual TipoCobertura TipoCobertura { get; set; }
        [InverseProperty("CoberturaProduto")]
        public virtual ICollection<BeneficioCobertura> BeneficioCobertura { get; set; }
        [InverseProperty("Cobertura")]
        public virtual ICollection<CoberturaCosseguro> CoberturaCosseguro { get; set; }
        [InverseProperty("Cobertura")]
        public virtual ICollection<CoberturaPlano> CoberturaPlano { get; set; }
        [InverseProperty("Cobertura")]
        public virtual ICollection<CoberturaResseguro> CoberturaResseguro { get; set; }
        [InverseProperty("Cobertura")]
        public virtual ICollection<Despesa> Despesa { get; set; }
        [InverseProperty("Cobertura")]
        public virtual ICollection<DespesaPlano> DespesaPlano { get; set; }
        [InverseProperty("Cobertura")]
        public virtual ICollection<DocumentosCoberturas> DocumentosCoberturas { get; set; }
        [InverseProperty("Cobertura")]
        public virtual ICollection<ExclusoesCobertura> ExclusoesCobertura { get; set; }
        [InverseProperty("CoberturaProduto")]
        public virtual ICollection<GarantiasCobertura> GarantiasCobertura { get; set; }
        [InverseProperty("CoberturaProduto")]
        public virtual ICollection<LimiteCobertura> LimiteCobertura { get; set; }
        [InverseProperty("CoberturaProduto")]
        public virtual ICollection<NivelRiscoCobertura> NivelRiscoCobertura { get; set; }
        [InverseProperty("CoberturaProduto")]
        public virtual ICollection<RiscosExcluidos> RiscosExcluidos { get; set; }
        [InverseProperty("CoberturaProduto")]
        public virtual ICollection<ServicosAdicionais> ServicosAdicionais { get; set; }
        [InverseProperty("CoberturaProduto")]
        public virtual ICollection<ServicosBase> ServicosBase { get; set; }
        [InverseProperty("Cobertura")]
        public virtual ICollection<SobrePremioCoberturaAdicional> SobrePremioCoberturaAdicionalCobertura { get; set; }
        [InverseProperty("CoberturaAdicional")]
        public virtual ICollection<SobrePremioCoberturaAdicional> SobrePremioCoberturaAdicionalCoberturaAdicional { get; set; }
    }
}