// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CodigoResponsabilidade
    {
        public CodigoResponsabilidade()
        {
            Reclamacao = new HashSet<Reclamacao>();
        }

        [StringLength(50)]
        public string IdCodigoResponsabilidade { get; set; }
        [StringLength(204)]
        public string Designacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("CodigoResponsabilidade")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("CodigoResponsabilidade")]
        public virtual ICollection<Reclamacao> Reclamacao { get; set; }
    }
}