// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CoeficienteLimiteIndemnizacaoProteseOrteses
    {
        [StringLength(50)]
        public string IdCoeficienteLimiteIndemnizacaoProteseOrteses { get; set; }
        public double? Valor { get; set; }
        public double? AgravamentoOuDesconto { get; set; }
        [StringLength(50)]
        public string CodCoeficienteLimiteIndemnizacaoOrteses { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string TipoOrtesesProteses { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("CoeficienteLimiteIndemnizacaoProteseOrteses")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("TipoOrtesesProteses")]
        [InverseProperty("CoeficienteLimiteIndemnizacaoProteseOrteses")]
        public virtual TipoOrtesesProteses TipoOrtesesProtesesNavigation { get; set; }
    }
}