// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Combustivel
    {
        public Combustivel()
        {
            ExemplarModeloAutomovel = new HashSet<ExemplarModeloAutomovel>();
            SistemaAquecimento = new HashSet<SistemaAquecimento>();
        }

        [StringLength(50)]
        public string IdCombustivel { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodCombustivel { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("Combustivel")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("Combustivel")]
        public virtual ICollection<ExemplarModeloAutomovel> ExemplarModeloAutomovel { get; set; }
        [InverseProperty("Combustivel")]
        public virtual ICollection<SistemaAquecimento> SistemaAquecimento { get; set; }
    }
}