// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CompetenciaArea
    {
        [StringLength(50)]
        public string IdCompetenciaArea { get; set; }
        public int NumCompetencia { get; set; }
        [StringLength(1000)]
        public string Designacao { get; set; }
        [Column("AreaID")]
        [StringLength(50)]
        public string AreaId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("AreaId")]
        [InverseProperty("CompetenciaArea")]
        public virtual Area Area { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("CompetenciaArea")]
        public virtual Estado Estado { get; set; }
    }
}