// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CondicaoAplicacaoAgravamento
    {
        [StringLength(50)]
        public string IdCondicaoTarifa { get; set; }
        [StringLength(50)]
        public string CondicaoAgravamentoId { get; set; }
        [StringLength(50)]
        public string AgravamentoId { get; set; }
        [StringLength(50)]
        public string Valor { get; set; }
        [StringLength(50)]
        public string UnidadeId { get; set; }
        [StringLength(50)]
        public string CodCondicaoTarifa { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }

        [ForeignKey("AgravamentoId")]
        [InverseProperty("CondicaoAplicacaoAgravamento")]
        public virtual Agravamento Agravamento { get; set; }
        [ForeignKey("CondicaoAgravamentoId")]
        [InverseProperty("CondicaoAplicacaoAgravamento")]
        public virtual CondicaoAgravamento CondicaoAgravamento { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("CondicaoAplicacaoAgravamento")]
        public virtual Estado Estado { get; set; }
    }
}