// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ContratoPlano
    {
        [StringLength(50)]
        public string IdContratoPlano { get; set; }
        [StringLength(50)]
        public string ContratoId { get; set; }
        [StringLength(50)]
        public string CodContratoPlano { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [ForeignKey("ContratoId")]
        [InverseProperty("ContratoPlano")]
        public virtual Contrato Contrato { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("ContratoPlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}