// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ContratoPrestadorEmpresa
    {
        [StringLength(50)]
        public string IdContratoPrestadorEmpresa { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataInicio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataFim { get; set; }
        public bool? Renovavel { get; set; }
        public bool? Exclusivo { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        public double? Valor { get; set; }
        [StringLength(50)]
        public string FormaPagamentoId { get; set; }
        [StringLength(50)]
        public string PessoaResponsavelFuncionarioId { get; set; }
        [StringLength(50)]
        public string PessoaResponsavelPrestador { get; set; }
        [StringLength(50)]
        public string InformacaoBancaria { get; set; }
        [Column(TypeName = "ntext")]
        public string Ambito { get; set; }
        [Column(TypeName = "ntext")]
        public string Objectivo { get; set; }
        public int? PrazoContrato { get; set; }
        public int? PeriodicidadePaga { get; set; }
        [StringLength(50)]
        public string Clausulas { get; set; }
        public double? TaxaJuros { get; set; }
        [StringLength(50)]
        public string NaturezaMovimento { get; set; }
        [StringLength(50)]
        public string CodTransacao { get; set; }
        public int? NumeroContrato { get; set; }
        public int? Referencia { get; set; }
        [StringLength(50)]
        public string ContratanteId { get; set; }
        [StringLength(50)]
        public string ContratadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAssinatura { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataVencimento { get; set; }
        [StringLength(50)]
        public string MoradaCobrancaContrato { get; set; }
        [StringLength(50)]
        public string MoradaAssinatura { get; set; }
        public int? NumeroPrestacoesPagas { get; set; }
        [Column("NumeroPrestacoesAPagar")]
        public int? NumeroPrestacoesApagar { get; set; }
        public double? TotalValorPago { get; set; }
        [Column("TotalValorAPagar")]
        public double? TotalValorApagar { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string ContaContabilistica { get; set; }
        [StringLength(50)]
        public string ReclamacaoId { get; set; }
        [StringLength(50)]
        public string NotaId { get; set; }
        [StringLength(50)]
        public string ActividadeId { get; set; }
        [StringLength(50)]
        public string Objecto { get; set; }
        [StringLength(50)]
        public string PessoaResponsavelFuncionario { get; set; }
        [StringLength(50)]
        public string LocalEmissaoId { get; set; }
        [StringLength(50)]
        public string TipoPagamentoId { get; set; }

        [ForeignKey("ActividadeId")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual Actividade Actividade { get; set; }
        [ForeignKey("Clausulas")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual Clausula ClausulasNavigation { get; set; }
        [ForeignKey("ContaContabilistica")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual PlanoContas ContaContabilisticaNavigation { get; set; }
        [ForeignKey("ContratadoId")]
        [InverseProperty("ContratoPrestadorEmpresaContratado")]
        public virtual Pessoa Contratado { get; set; }
        [ForeignKey("ContratanteId")]
        [InverseProperty("ContratoPrestadorEmpresaContratante")]
        public virtual Pessoa Contratante { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FormaPagamentoId")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual FormaPagamento FormaPagamento { get; set; }
        [ForeignKey("InformacaoBancaria")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual InformacaoBancaria InformacaoBancariaNavigation { get; set; }
        [ForeignKey("LocalEmissaoId")]
        [InverseProperty("ContratoPrestadorEmpresaLocalEmissao")]
        public virtual Endereco LocalEmissao { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("MoradaAssinatura")]
        [InverseProperty("ContratoPrestadorEmpresaMoradaAssinaturaNavigation")]
        public virtual Endereco MoradaAssinaturaNavigation { get; set; }
        [ForeignKey("MoradaCobrancaContrato")]
        [InverseProperty("ContratoPrestadorEmpresaMoradaCobrancaContratoNavigation")]
        public virtual Endereco MoradaCobrancaContratoNavigation { get; set; }
        [ForeignKey("NaturezaMovimento")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual NaturezaMovimento NaturezaMovimentoNavigation { get; set; }
        [ForeignKey("NotaId")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual Notas Nota { get; set; }
        [ForeignKey("PessoaResponsavelFuncionarioId")]
        [InverseProperty("ContratoPrestadorEmpresaPessoaResponsavelFuncionario1")]
        public virtual Pessoa PessoaResponsavelFuncionario1 { get; set; }
        [ForeignKey("PessoaResponsavelFuncionario")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual Funcionario PessoaResponsavelFuncionarioNavigation { get; set; }
        [ForeignKey("PessoaResponsavelPrestador")]
        [InverseProperty("ContratoPrestadorEmpresaPessoaResponsavelPrestadorNavigation")]
        public virtual Pessoa PessoaResponsavelPrestadorNavigation { get; set; }
        [ForeignKey("ReclamacaoId")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual Reclamacao Reclamacao { get; set; }
        [ForeignKey("TipoPagamentoId")]
        [InverseProperty("ContratoPrestadorEmpresa")]
        public virtual TipoPagamento TipoPagamento { get; set; }
    }
}