// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Contrato
    {
        public Contrato()
        {
            CanalContratos = new HashSet<CanalContratos>();
            Comissionamento = new HashSet<Comissionamento>();
            ContaFinanceiraNavigation = new HashSet<ContaFinanceira>();
            Contratados = new HashSet<Contratados>();
            ContratadosAssinantes = new HashSet<ContratadosAssinantes>();
            ContratantesAssinantes = new HashSet<ContratantesAssinantes>();
            ContratoCae = new HashSet<ContratoCae>();
            ContratoClausula = new HashSet<ContratoClausula>();
            ContratoFormaPagamento = new HashSet<ContratoFormaPagamento>();
            ContratoMoeda = new HashSet<ContratoMoeda>();
            ContratoPlano = new HashSet<ContratoPlano>();
            ContratoResseguro = new HashSet<ContratoResseguro>();
            ContratoSegmentos = new HashSet<ContratoSegmentos>();
            FidelizacaoContrato = new HashSet<FidelizacaoContrato>();
            InformacaoBancariaContrato = new HashSet<InformacaoBancariaContrato>();
            LimiteComissionamentoProdutor = new HashSet<LimiteComissionamentoProdutor>();
            PessoaContactoContratado = new HashSet<PessoaContactoContratado>();
            PessoaContactoContratante = new HashSet<PessoaContactoContratante>();
            TipoComissionamentoResseguro = new HashSet<TipoComissionamentoResseguro>();
            TipoSegmentoContrato = new HashSet<TipoSegmentoContrato>();
        }

        [StringLength(50)]
        public string IdContrato { get; set; }
        //public long NumeroContrato { get; set; }
        [StringLength(500)]
        public string Referencia { get; set; }
        [StringLength(50)]
        public string ContratanteId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataAssinatura { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataVencimento { get; set; }
        public double Valor { get; set; }
        public long? NumeroPrestacoesPagas { get; set; }
        [Column("NumeroPrestacoesAPagar")]
        public long? NumeroPrestacoesApagar { get; set; }
        public double? TotalValorPago { get; set; }
        [Column("TotalValorAPagar")]
        public double? TotalValorApagar { get; set; }
        [Required]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodContrato { get; set; }
        [StringLength(50)]
        public string EnderecoId { get; set; }
        [StringLength(50)]
        public string MoradaCobrancaContratoId { get; set; }
        [StringLength(50)]
        public string MoradaAssinaturaId { get; set; }
        [StringLength(50)]
        public string TipoPagamentoId { get; set; }
        [StringLength(50)]
        public string ContaFinanceiraId { get; set; }
        [StringLength(50)]
        public string TipoContratoId { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string DuracaoTipoContratoId { get; set; }
        public int? NumDias { get; set; }
        [StringLength(50)]
        public string CentroCustoId { get; set; }
        [StringLength(50)]
        public string CentroResponsabilidadeId { get; set; }
        public double? Cedencia { get; set; }
        public double? Retencao { get; set; }
        [StringLength(50)]
        public string FraccionamentoId { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        [StringLength(50)]
        public string FormaPagamentoId { get; set; }
        [StringLength(50)]
        public string TipoOperacaoId { get; set; }
        public bool? FazRetencaoNaFonte { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DiaPagamento { get; set; }
        [StringLength(50)]
        public string ContaFinanceira { get; set; }
        [StringLength(50)]
        public string Ano { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataFinal { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataRenovacao { get; set; }
        [StringLength(50)]
        public string PrazoAlteracao { get; set; }
        [StringLength(50)]
        public string PrazoPreAviso { get; set; }
        [StringLength(50)]
        public string FormaFacturacao { get; set; }
        [StringLength(50)]
        public string MoradaAssinatura { get; set; }
        [StringLength(50)]
        public string MoradaCobranca { get; set; }
        [StringLength(50)]
        public string ContratadoId { get; set; }
        [StringLength(50)]
        public string ProdutorId { get; set; }

        [ForeignKey("CentroCustoId")]
        [InverseProperty("Contrato")]
        public virtual CentroCusto CentroCusto { get; set; }
        [ForeignKey("CentroResponsabilidadeId")]
        [InverseProperty("Contrato")]
        public virtual CentroResponsabilidade CentroResponsabilidade { get; set; }
        [ForeignKey("ContaFinanceira")]
        [InverseProperty("ContratoContaFinanceira1")]
        public virtual ContaFinanceira ContaFinanceira1 { get; set; }
        [ForeignKey("ContaFinanceiraId")]
        [InverseProperty("ContratoContaFinanceira2")]
        public virtual ContaFinanceira ContaFinanceira2 { get; set; }
        [ForeignKey("ContratadoId")]
        [InverseProperty("ContratoContratado")]
        public virtual Pessoa Contratado { get; set; }
        [ForeignKey("ContratanteId")]
        [InverseProperty("ContratoContratante")]
        public virtual Pessoa Contratante { get; set; }
        [ForeignKey("DuracaoTipoContratoId")]
        [InverseProperty("Contrato")]
        public virtual DuracaoTipoContrato DuracaoTipoContrato { get; set; }
        [ForeignKey("EnderecoId")]
        [InverseProperty("ContratoEndereco")]
        public virtual Endereco Endereco { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Contrato")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FormaFacturacao")]
        [InverseProperty("ContratoFormaFacturacaoNavigation")]
        public virtual Fraccionamento FormaFacturacaoNavigation { get; set; }
        [ForeignKey("FormaPagamentoId")]
        [InverseProperty("Contrato")]
        public virtual FormaPagamento FormaPagamento { get; set; }
        [ForeignKey("FraccionamentoId")]
        [InverseProperty("ContratoFraccionamento")]
        public virtual Fraccionamento Fraccionamento { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("Contrato")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("MoradaAssinaturaId")]
        [InverseProperty("ContratoMoradaAssinaturaNavigation")]
        public virtual Endereco MoradaAssinaturaNavigation { get; set; }
        [ForeignKey("MoradaCobrancaContratoId")]
        [InverseProperty("ContratoMoradaCobrancaContrato")]
        public virtual Endereco MoradaCobrancaContrato { get; set; }
        [ForeignKey("PrazoAlteracao")]
        [InverseProperty("ContratoPrazoAlteracaoNavigation")]
        public virtual Fraccionamento PrazoAlteracaoNavigation { get; set; }
        [ForeignKey("PrazoPreAviso")]
        [InverseProperty("ContratoPrazoPreAvisoNavigation")]
        public virtual Fraccionamento PrazoPreAvisoNavigation { get; set; }
        [ForeignKey("ProdutorId")]
        [InverseProperty("ContratoProdutor")]
        public virtual Pessoa Produtor { get; set; }
        [ForeignKey("TipoContratoId")]
        [InverseProperty("Contrato")]
        public virtual TipoContrato TipoContrato { get; set; }
        [ForeignKey("TipoOperacaoId")]
        [InverseProperty("Contrato")]
        public virtual TipoOperacao TipoOperacao { get; set; }
        [ForeignKey("TipoPagamentoId")]
        [InverseProperty("Contrato")]
        public virtual TipoPagamento TipoPagamento { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<CanalContratos> CanalContratos { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<Comissionamento> Comissionamento { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContaFinanceira> ContaFinanceiraNavigation { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<Contratados> Contratados { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContratadosAssinantes> ContratadosAssinantes { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContratantesAssinantes> ContratantesAssinantes { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContratoCae> ContratoCae { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContratoClausula> ContratoClausula { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContratoFormaPagamento> ContratoFormaPagamento { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContratoMoeda> ContratoMoeda { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContratoPlano> ContratoPlano { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContratoResseguro> ContratoResseguro { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<ContratoSegmentos> ContratoSegmentos { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<FidelizacaoContrato> FidelizacaoContrato { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<InformacaoBancariaContrato> InformacaoBancariaContrato { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<LimiteComissionamentoProdutor> LimiteComissionamentoProdutor { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<PessoaContactoContratado> PessoaContactoContratado { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<PessoaContactoContratante> PessoaContactoContratante { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<TipoComissionamentoResseguro> TipoComissionamentoResseguro { get; set; }
        [InverseProperty("Contrato")]
        public virtual ICollection<TipoSegmentoContrato> TipoSegmentoContrato { get; set; }
    }
}