// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CriterioPlano
    {
        [StringLength(50)]
        public string IdCriterioPlano { get; set; }
        [StringLength(50)]
        public string ProvinciaPlanoId { get; set; }
        [StringLength(50)]
        public string CodCriterioPlano { get; set; }
        [StringLength(50)]
        public string TipoSegmentoPlanoId { get; set; }
        [StringLength(50)]
        public string SectorActividadePlano { get; set; }
        [StringLength(50)]
        public string CanalPlanoId { get; set; }
        [StringLength(50)]
        public string FormaPagamentoPlano { get; set; }
        public double? PremioMin { get; set; }
        public double? PremioMax { get; set; }
        [StringLength(50)]
        public string PapelPlanoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("CanalPlanoId")]
        [InverseProperty("CriterioPlano")]
        public virtual CanalPlano CanalPlano { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("CriterioPlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FormaPagamentoPlano")]
        [InverseProperty("CriterioPlano")]
        public virtual FormaPagamentoPlano FormaPagamentoPlanoNavigation { get; set; }
        [ForeignKey("PapelPlanoId")]
        [InverseProperty("CriterioPlano")]
        public virtual PapelPlano PapelPlano { get; set; }
        [ForeignKey("ProvinciaPlanoId")]
        [InverseProperty("CriterioPlano")]
        public virtual ProvinciaPlano ProvinciaPlano { get; set; }
        [ForeignKey("SectorActividadePlano")]
        [InverseProperty("CriterioPlano")]
        public virtual SectorActividadePlano SectorActividadePlanoNavigation { get; set; }
        [ForeignKey("TipoSegmentoPlanoId")]
        [InverseProperty("CriterioPlano")]
        public virtual TipoSegmentoPlano TipoSegmentoPlano { get; set; }
    }
}