// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class CriterioComissionamento
    {
        public CriterioComissionamento()
        {
            CanalComissionamento = new HashSet<CanalComissionamento>();
            FidelizacaoComissionamento = new HashSet<FidelizacaoComissionamento>();
            ProvinciaComissionamento = new HashSet<ProvinciaComissionamento>();
            TipoSegmentoComissionamento = new HashSet<TipoSegmentoComissionamento>();
        }

        [StringLength(50)]
        public string IdCriterioComissionamento { get; set; }
        [StringLength(50)]
        public string ComissionamentoId { get; set; }
        [StringLength(50)]
        public string CanalId { get; set; }
        [StringLength(50)]
        public string SegmentoPlanoId { get; set; }
        [StringLength(50)]
        public string LimiteComissionamentoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodCriterioComissionamento { get; set; }

        [ForeignKey("CanalId")]
        [InverseProperty("CriterioComissionamento")]
        public virtual Canal Canal { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("CriterioComissionamento")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("SegmentoPlanoId")]
        [InverseProperty("CriterioComissionamento")]
        public virtual TipoSegmentoPlano SegmentoPlano { get; set; }
        [InverseProperty("CriterioComissionamento")]
        public virtual ICollection<CanalComissionamento> CanalComissionamento { get; set; }
        [InverseProperty("CriterioComissionamento")]
        public virtual ICollection<FidelizacaoComissionamento> FidelizacaoComissionamento { get; set; }
        [InverseProperty("CriterioComissionamento")]
        public virtual ICollection<ProvinciaComissionamento> ProvinciaComissionamento { get; set; }
        [InverseProperty("CriterioComissionamento")]
        public virtual ICollection<TipoSegmentoComissionamento> TipoSegmentoComissionamento { get; set; }
    }
}