// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Deficiencia
    {
        public Deficiencia()
        {
            Pessoa = new HashSet<Pessoa>();
        }

        [StringLength(50)]
        public string IdDeficiencia { get; set; }
        [StringLength(100)]
        public string Descricao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodDeficiencia { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("Deficiencia")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("Deficiencia")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}