// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class DescricaoBeneficioCobertura
    {
        [StringLength(50)]
        public string IdDescricaoBeneficioCobertura { get; set; }
        [StringLength(500)]
        public string Descricao { get; set; }
        [StringLength(50)]
        public string CodDescricaoBeneficioCobertura { get; set; }
        [StringLength(50)]
        public string BeneficioCoberturaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }

        [ForeignKey("BeneficioCoberturaId")]
        [InverseProperty("DescricaoBeneficioCobertura")]
        public virtual BeneficioCobertura BeneficioCobertura { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("DescricaoBeneficioCobertura")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("DescricaoBeneficioCobertura")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}