// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class DescontoPessoaPlano
    {
        [StringLength(50)]
        public string IdDescontoPessoaPlano { get; set; }
        [StringLength(50)]
        public string CodDescontoPessoaPlano { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string DescontoPessoaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("DescontoPessoaId")]
        [InverseProperty("DescontoPessoaPlano")]
        public virtual DescontoPessoa DescontoPessoa { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("DescontoPessoaPlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("DescontoPessoaPlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}