// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class DespesaPlano
    {
        [StringLength(50)]
        public string IdDespesaPlano { get; set; }
        [StringLength(50)]
        public string DespesaId { get; set; }
        [StringLength(50)]
        public string CoberturaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string CodDespesaPlano { get; set; }

        [ForeignKey("CoberturaId")]
        [InverseProperty("DespesaPlano")]
        public virtual Cobertura Cobertura { get; set; }
        [ForeignKey("DespesaId")]
        [InverseProperty("DespesaPlano")]
        public virtual Despesa Despesa { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("DespesaPlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("DespesaPlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}