// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class DespesaSeleccionada
    {
        [StringLength(50)]
        public string IdDespesaSeleccionada { get; set; }
        public double? Valor { get; set; }
        [Column("CotacaoID")]
        [StringLength(50)]
        public string CotacaoId { get; set; }
        [StringLength(50)]
        public string PessoaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("ApoliceID")]
        [StringLength(50)]
        public string ApoliceId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("DespesaID")]
        [StringLength(50)]
        public string DespesaId { get; set; }
        [StringLength(50)]
        public string CodDespesaSeleccionada { get; set; }

        [ForeignKey("ApoliceId")]
        [InverseProperty("DespesaSeleccionada")]
        public virtual Apolice Apolice { get; set; }
        [ForeignKey("CotacaoId")]
        [InverseProperty("DespesaSeleccionada")]
        public virtual Cotacao Cotacao { get; set; }
        [ForeignKey("DespesaId")]
        [InverseProperty("DespesaSeleccionada")]
        public virtual Despesa Despesa { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("DespesaSeleccionada")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("DespesaSeleccionada")]
        public virtual Pessoa Pessoa { get; set; }
    }
}