// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class DimensaoEmpresa
    {
        public DimensaoEmpresa()
        {
            Pessoa = new HashSet<Pessoa>();
            TipoSegmento = new HashSet<TipoSegmento>();
        }

        [StringLength(50)]
        public string IdDimensaoEmpresa { get; set; }
        [StringLength(10)]
        public string CodDimensaoEmpresa { get; set; }
        public int? MinFuncionarios { get; set; }
        public int? MaxFuncionarios { get; set; }
        public double Percentagem { get; set; }
        [StringLength(300)]
        public string Designacao { get; set; }
        [Column("TipoEmpresaID")]
        [StringLength(50)]
        public string TipoEmpresaId { get; set; }
        [Required]
        public bool? IsTaxa { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("DimensaoEmpresa")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("TipoEmpresaId")]
        [InverseProperty("DimensaoEmpresa")]
        public virtual TipoEmpresa TipoEmpresa { get; set; }
        [InverseProperty("DimensaoEmpresa")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
        [InverseProperty("DimensaoEmpresa")]
        public virtual ICollection<TipoSegmento> TipoSegmento { get; set; }
    }
}