// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class DocumentosObjectoEnvolvido
    {
        [StringLength(50)]
        public string IdDocumentosAutomovel { get; set; }
        [StringLength(500)]
        public string Designacao { get; set; }
        [StringLength(800)]
        public string CaminhoFicheiro { get; set; }
        [Column("ObjectoEnvolvidoID")]
        [StringLength(50)]
        public string ObjectoEnvolvidoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("DocumentosObjectoEnvolvido")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("ObjectoEnvolvidoId")]
        [InverseProperty("DocumentosObjectoEnvolvido")]
        public virtual ObjectoEnvolvido ObjectoEnvolvido { get; set; }
    }
}