// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class DocumentoMembroAssegurado
    {
        [StringLength(50)]
        public string IdDocumentoMembroAssegurado { get; set; }
        [StringLength(50)]
        public string MembroAsseguradoId { get; set; }
        [StringLength(50)]
        public string TipoDocumentoIdentificacaoId { get; set; }
        [StringLength(50)]
        public string ApoliceId { get; set; }
        [StringLength(50)]
        public string CodDocumentoMembroAssegurado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string NumeroDocumemnto { get; set; }

        [ForeignKey("ApoliceId")]
        [InverseProperty("DocumentoMembroAssegurado")]
        public virtual Apolice Apolice { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("DocumentoMembroAssegurado")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MembroAsseguradoId")]
        [InverseProperty("DocumentoMembroAssegurado")]
        public virtual MembroAssegurado MembroAssegurado { get; set; }
        [ForeignKey("TipoDocumentoIdentificacaoId")]
        [InverseProperty("DocumentoMembroAssegurado")]
        public virtual TipoDocumentoIdentificacao TipoDocumentoIdentificacao { get; set; }
    }
}