// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class DocumentosLesado
    {
        [StringLength(50)]
        public string IdDocumentosLesado { get; set; }
        [StringLength(500)]
        public string Designacao { get; set; }
        [StringLength(800)]
        public string CaminhoFicheiro { get; set; }
        [Column("LesadoID")]
        [StringLength(50)]
        public string LesadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("DocumentosLesado")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LesadoId")]
        [InverseProperty("DocumentosLesado")]
        public virtual Lesado Lesado { get; set; }
    }
}