// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class EncargosTipoConta
    {
        [StringLength(50)]
        public string IdEncargosTipoConta { get; set; }
        [StringLength(50)]
        public string EncargosId { get; set; }
        [StringLength(50)]
        public string CodEncargosTipoConta { get; set; }
        [StringLength(50)]
        public string TipoContaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [ForeignKey("EncargosId")]
        [InverseProperty("EncargosTipoConta")]
        public virtual Encargos Encargos { get; set; }
        [ForeignKey("TipoContaId")]
        [InverseProperty("EncargosTipoConta")]
        public virtual TipoConta TipoConta { get; set; }
    }
}