// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class EnderecoPessoa
    {
        [StringLength(50)]
        public string IdEnderecoPessoa { get; set; }
        public bool? Principal { get; set; }
        [Column("EnderecoID")]
        [StringLength(50)]
        public string EnderecoId { get; set; }
        [StringLength(50)]
        public string PessoaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodEnderecoPessoa { get; set; }

        [ForeignKey("EnderecoId")]
        [InverseProperty("EnderecoPessoa")]
        public virtual Endereco Endereco { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("EnderecoPessoa")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("EnderecoPessoa")]
        public virtual Pessoa Pessoa { get; set; }
    }
}