// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class EntidadeEmpregadora
    {
        [StringLength(50)]
        public string IdEntidadeEmpregadora { get; set; }
        [Column("NIF")]
        [StringLength(13)]
        public string Nif { get; set; }
        [Column("CAEID")]
        [StringLength(50)]
        public string Caeid { get; set; }
        [StringLength(50)]
        public string ClassificacaoEntidadeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(100)]
        public string Nome { get; set; }

        [ForeignKey("Caeid")]
        [InverseProperty("EntidadeEmpregadora")]
        public virtual Cae Cae { get; set; }
        [ForeignKey("ClassificacaoEntidadeId")]
        [InverseProperty("EntidadeEmpregadora")]
        public virtual ClassificacaoEntidade ClassificacaoEntidade { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("EntidadeEmpregadora")]
        public virtual Estado Estado { get; set; }
    }
}