// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class EstadoCivilPlano
    {
        [StringLength(50)]
        public string IdEstadoCivilPlano { get; set; }
        [StringLength(50)]
        public string CodEstadoCivilPlano { get; set; }
        [StringLength(50)]
        public string EstadoCivilId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("EstadoCivilPlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("EstadoCivilId")]
        [InverseProperty("EstadoCivilPlano")]
        public virtual EstadoCivil EstadoCivil { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("EstadoCivilPlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}