// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Excedente
    {
        [StringLength(50)]
        public string IdExcedente { get; set; }
        public double? Cedencia { get; set; }
        [StringLength(50)]
        public string ComissaoId { get; set; }
        [StringLength(50)]
        public string SinistroId { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        public double? ValorLiquido { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string EntidadeId { get; set; }

        [ForeignKey("ComissaoId")]
        [InverseProperty("Excedente")]
        public virtual Comissao Comissao { get; set; }
        [ForeignKey("EntidadeId")]
        [InverseProperty("Excedente")]
        public virtual Pessoa Entidade { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Excedente")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("Excedente")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("SinistroId")]
        [InverseProperty("Excedente")]
        public virtual Sinistro Sinistro { get; set; }
    }
}