// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ExclusoesPlano
    {
        [StringLength(50)]
        public string IdExclusoesPlano { get; set; }
        [Column(TypeName = "text")]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string CodExclusoesPlano { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [StringLength(50)]
        public string ExclusaoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ExclusoesPlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("ExclusaoId")]
        [InverseProperty("ExclusoesPlano")]
        public virtual Exclusoes Exclusao { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("ExclusoesPlano")]
        public virtual LinhaProduto LinhaProduto { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("ExclusoesPlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}