// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class FaixaEtaria
    {
        public FaixaEtaria()
        {
            Pessoa = new HashSet<Pessoa>();
        }

        [StringLength(50)]
        public string IdFaixaEtaria { get; set; }
        [StringLength(300)]
        public string Designacao { get; set; }
        public int IdadeMin { get; set; }
        public int IdadeMax { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("FaixaEtaria")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("FaixaEtaria")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}