// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class FormaPagamentoPlano
    {
        public FormaPagamentoPlano()
        {
            ComissionamentoPlano = new HashSet<ComissionamentoPlano>();
            CriterioPlano = new HashSet<CriterioPlano>();
        }

        [StringLength(50)]
        public string IdFormaPagamentoPlano { get; set; }
        [StringLength(50)]
        public string FormaPagamentoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string PessoaId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("FormaPagamentoPlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FormaPagamentoId")]
        [InverseProperty("FormaPagamentoPlano")]
        public virtual FormaPagamento FormaPagamento { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("FormaPagamentoPlano")]
        public virtual Pessoa Pessoa { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("FormaPagamentoPlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [InverseProperty("FormaPagamentoPlano")]
        public virtual ICollection<ComissionamentoPlano> ComissionamentoPlano { get; set; }
        [InverseProperty("FormaPagamentoPlanoNavigation")]
        public virtual ICollection<CriterioPlano> CriterioPlano { get; set; }
    }
}