// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class FormaLiquidacaoPremio
    {
        public FormaLiquidacaoPremio()
        {
            Cotacao = new HashSet<Cotacao>();
            FormaLiquidacaoPremioPlano = new HashSet<FormaLiquidacaoPremioPlano>();
            FraccionamentoPlano = new HashSet<FraccionamentoPlano>();
            HablitacoesLiterariasPlano = new HashSet<HablitacoesLiterariasPlano>();
            RendimentosPessoa = new HashSet<RendimentosPessoa>();
        }

        [StringLength(50)]
        public string IdFormaLiquidacaoPremio { get; set; }
        [StringLength(200)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodFormaLiquidacaoPremio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(500)]
        public string CaminhoIcone { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("FormaLiquidacaoPremio")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("FormaLiquidacaoPremio")]
        public virtual ICollection<Cotacao> Cotacao { get; set; }
        [InverseProperty("FormaLiquidacaoPremio")]
        public virtual ICollection<FormaLiquidacaoPremioPlano> FormaLiquidacaoPremioPlano { get; set; }
        [InverseProperty("FormaLiquidacaoPremio")]
        public virtual ICollection<FraccionamentoPlano> FraccionamentoPlano { get; set; }
        [InverseProperty("FormaLiquidacaoPremio")]
        public virtual ICollection<HablitacoesLiterariasPlano> HablitacoesLiterariasPlano { get; set; }
        [InverseProperty("FormaLiquidacaoPremio")]
        public virtual ICollection<RendimentosPessoa> RendimentosPessoa { get; set; }
    }
}