// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class FraccionamentoPlano
    {
        [StringLength(50)]
        public string IdFraccionamentoPlano { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string PessoaId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string FraccionamentoId { get; set; }
        [StringLength(50)]
        public string FormaLiquidacaoPremioId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("FraccionamentoPlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FormaLiquidacaoPremioId")]
        [InverseProperty("FraccionamentoPlano")]
        public virtual FormaLiquidacaoPremio FormaLiquidacaoPremio { get; set; }
        [ForeignKey("FraccionamentoId")]
        [InverseProperty("FraccionamentoPlano")]
        public virtual Fraccionamento Fraccionamento { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("FraccionamentoPlano")]
        public virtual Pessoa Pessoa { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("FraccionamentoPlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}