// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class GrauParentesco
    {
        public GrauParentesco()
        {
            Beneficiario = new HashSet<Beneficiario>();
            Dependente = new HashSet<Dependente>();
            ReembolsoTratamentoDentario = new HashSet<ReembolsoTratamentoDentario>();
        }

        [StringLength(50)]
        public string IdGrau { get; set; }
        [StringLength(2048)]
        public string Designacao { get; set; }
        public double PercentagemIndemnizacao { get; set; }
        [StringLength(1000)]
        public string DescricaoIndemnizacao { get; set; }
        [StringLength(1000)]
        public string DescricaoMaxIndemnizacao { get; set; }
        [StringLength(10)]
        public string CodGrauParentesco { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Required]
        public bool? IsTaxa { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("GrauParentesco")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("GrauParentesco")]
        public virtual ICollection<Beneficiario> Beneficiario { get; set; }
        [InverseProperty("GrauParentesco")]
        public virtual ICollection<Dependente> Dependente { get; set; }
        [InverseProperty("GrauParentescoNavigation")]
        public virtual ICollection<ReembolsoTratamentoDentario> ReembolsoTratamentoDentario { get; set; }
    }
}