// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class GrupoEtario
    {
        [StringLength(50)]
        public string IdGrupoEtario { get; set; }
        public double? IdadeMin { get; set; }
        public double? IdadeMax { get; set; }
        [StringLength(50)]
        public string ModalidadeSeguroId { get; set; }
        [StringLength(50)]
        public string FormaContratacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string CodGrupoEtario { get; set; }

        [ForeignKey("FormaContratacaoId")]
        [InverseProperty("GrupoEtario")]
        public virtual FormaContratacao FormaContratacao { get; set; }
        [ForeignKey("ModalidadeSeguroId")]
        [InverseProperty("GrupoEtario")]
        public virtual ModalidadeSeguro ModalidadeSeguro { get; set; }
    }
}