// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class GrupoPessoas
    {
        public GrupoPessoas()
        {
            MembrosGrupo = new HashSet<MembrosGrupo>();
        }

        [StringLength(50)]
        public string IdGrupo { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [Column("AdministradorID")]
        [StringLength(50)]
        public string AdministradorId { get; set; }
        [Column("TipoGrupoID")]
        [StringLength(50)]
        public string TipoGrupoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [StringLength(50)]
        public string CodGrupoPessoas { get; set; }

        [ForeignKey("AdministradorId")]
        [InverseProperty("GrupoPessoas")]
        public virtual Pessoa Administrador { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("GrupoPessoas")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("TipoGrupoId")]
        [InverseProperty("GrupoPessoas")]
        public virtual TipoGrupo TipoGrupo { get; set; }
        [InverseProperty("Grupo")]
        public virtual ICollection<MembrosGrupo> MembrosGrupo { get; set; }
    }
}