// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class HabilitacoesLiterarias
    {
        public HabilitacoesLiterarias()
        {
            HabilitacoesLiterariasPessoa = new HashSet<HabilitacoesLiterariasPessoa>();
        }

        [StringLength(50)]
        public string IdHabilitacoesLiterarias { get; set; }
        [StringLength(2048)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodHabilitacoesLiterarias { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("HabilitacoesLiterarias")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("HabilitacoesLiterarias")]
        public virtual ICollection<HabilitacoesLiterariasPessoa> HabilitacoesLiterariasPessoa { get; set; }
    }
}