// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class HistoricoPrecarioProduto
    {
        [StringLength(50)]
        public string IdHistoricoPrecarioProduto { get; set; }
        public double? PrecoBase { get; set; }
        public int? QtdDiaMin { get; set; }
        public int? QtdDiaMax { get; set; }
        [StringLength(100)]
        public string Descricao { get; set; }
        [Column("PlanoProdutoID")]
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string IdPrecarioProduto { get; set; }
        [Column("CanalID")]
        [StringLength(50)]
        public string CanalId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("HistoricoPrecarioProduto")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("HistoricoPrecarioProduto")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("HistoricoPrecarioProduto")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}