// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class HistoricoEncargo
    {
        [StringLength(50)]
        public string IdHistoricoEncargo { get; set; }
        [StringLength(50)]
        public string IdEncargo { get; set; }
        public double? TaxaMinEncargo { get; set; }
        [Column("TipoEncargoID")]
        [StringLength(50)]
        public string TipoEncargoId { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("PlanoProdutoID")]
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(10)]
        public string CodEncargo { get; set; }
        public double? ValorMinPremioSimples { get; set; }
        public double? ValorMaxPremioSimples { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public double? TaxaMaxEncargo { get; set; }
        public double? ValorMinEncargo { get; set; }
        public double? ValorMaxEncargo { get; set; }
        public bool? IsTaxa { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [Column("PrecarioProdutoID")]
        [StringLength(50)]
        public string PrecarioProdutoId { get; set; }
    }
}