// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class HistoricoDesconto
    {
        [StringLength(50)]
        public string IdHistoricoDesconto { get; set; }
        [StringLength(50)]
        public string IdDesconto { get; set; }
        public double? TaxaDesconto { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataFim { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("TipoDescontoID")]
        [StringLength(50)]
        public string TipoDescontoId { get; set; }
        [Column("PlanoProdutoID")]
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(10)]
        public string CodDesconto { get; set; }
        public double? ValorMinPremioSimples { get; set; }
        public double? ValorMaxPremioSimples { get; set; }
        [Column("PapelID")]
        [StringLength(50)]
        public string PapelId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public double? TaxaMaxDesconto { get; set; }
        public double? ValorMinDesconto { get; set; }
        public double? ValorMaxDesconto { get; set; }
        public bool? IsTaxa { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [Column("PrecarioProdutoID")]
        [StringLength(50)]
        public string PrecarioProdutoId { get; set; }
    }
}