// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class HistoricoDespesa
    {
        [StringLength(50)]
        public string IdHistoricoDespesa { get; set; }
        [StringLength(50)]
        public string IdDespesa { get; set; }
        public double? ValorMin { get; set; }
        [Column("TipoDespesaID")]
        [StringLength(50)]
        public string TipoDespesaId { get; set; }
        [Column("PlanoProdutoID")]
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(10)]
        public string CodDespesa { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public double? ValorMax { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [Column("PrecarioProdutoID")]
        [StringLength(50)]
        public string PrecarioProdutoId { get; set; }
        public bool? IsTaxa { get; set; }
    }
}