// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ImagemProduto
    {
        [StringLength(50)]
        public string IdImagemProduto { get; set; }
        [StringLength(512)]
        public string CaminhoIcone { get; set; }
        [Column("TipoImagemProdutoID")]
        [StringLength(50)]
        public string TipoImagemProdutoId { get; set; }
        [Column("ProdutoID")]
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [StringLength(10)]
        public string CodImagemProduto { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("LinhaProdutoID")]
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("PlanoProdutoID")]
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [Column("PortfolioProdutoID")]
        [StringLength(50)]
        public string PortfolioProdutoId { get; set; }
        public byte[] ImagemByte { get; set; }
        [StringLength(300)]
        public string CaminhoImagem { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ImagemProduto")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("ImagemProduto")]
        public virtual LinhaProduto LinhaProduto { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("ImagemProduto")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("PortfolioProdutoId")]
        [InverseProperty("ImagemProduto")]
        public virtual PortfolioProduto PortfolioProduto { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("ImagemProduto")]
        public virtual Produto Produto { get; set; }
        [ForeignKey("TipoImagemProdutoId")]
        [InverseProperty("ImagemProduto")]
        public virtual TipoImagemProduto TipoImagemProduto { get; set; }
    }
}