// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ImpostoPrecario
    {
        public ImpostoPrecario()
        {
            Encargos = new HashSet<Encargos>();
        }

        [StringLength(50)]
        public string IdImpostoPrecario { get; set; }
        [StringLength(50)]
        public string ImpostoId { get; set; }
        [StringLength(50)]
        public string PrecarioProdutoId { get; set; }
        [StringLength(50)]
        public string CodImpostoPrecario { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string ZonaId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ImpostoPrecario")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("ImpostoId")]
        [InverseProperty("ImpostoPrecario")]
        public virtual Imposto Imposto { get; set; }
        [ForeignKey("PrecarioProdutoId")]
        [InverseProperty("ImpostoPrecario")]
        public virtual PrecarioProduto PrecarioProduto { get; set; }
        [ForeignKey("ZonaId")]
        [InverseProperty("ImpostoPrecario")]
        public virtual Zona Zona { get; set; }
        [InverseProperty("ImpostoPrecario")]
        public virtual ICollection<Encargos> Encargos { get; set; }
    }
}