// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ImpostoPlano
    {
        [StringLength(50)]
        public string IdImpostoPlano { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string ImpostoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [ForeignKey("ImpostoId")]
        [InverseProperty("ImpostoPlano")]
        public virtual Imposto Imposto { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("ImpostoPlano")]
        public virtual PlanoProduto PlanoProduto { get; set; }
    }
}