// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class IndiceCargaPneu
    {
        public IndiceCargaPneu()
        {
            Pneu = new HashSet<Pneu>();
        }

        [StringLength(50)]
        public string IdIndiceCargaPneu { get; set; }
        public int? Indice { get; set; }
        public int? Carga { get; set; }
        [StringLength(10)]
        public string CodIndiceCargaPneu { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("IndiceCargaPneu")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("IndiceCargaPneu")]
        public virtual ICollection<Pneu> Pneu { get; set; }
    }
}