// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    [Table("InformacaoBancariaPOS")]
    public partial class InformacaoBancariaPos
    {
        [Column("IdInformacaoBancariaPOS")]
        [StringLength(50)]
        public string IdInformacaoBancariaPos { get; set; }
        [StringLength(50)]
        public string InformacaoBancariaId { get; set; }
        [Column("POSId")]
        [StringLength(50)]
        public string Posid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column("CodInformacaoBancariaPOS")]
        [StringLength(50)]
        public string CodInformacaoBancariaPos { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("InformacaoBancariaPos")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("InformacaoBancariaId")]
        [InverseProperty("InformacaoBancariaPos")]
        public virtual InformacaoBancaria InformacaoBancaria { get; set; }
        [ForeignKey("Posid")]
        [InverseProperty("InformacaoBancariaPos")]
        public virtual Pos Pos { get; set; }
    }
}