// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class InformacaoSuporte
    {
        [StringLength(50)]
        public string IdInformacaoSuporte { get; set; }
        [StringLength(100)]
        public string Titulo { get; set; }
        [StringLength(1000)]
        public string Conteudo { get; set; }
        [Column("ProdutoID")]
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [StringLength(10)]
        public string CodInformacaoSuporte { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("LinhaProdutoID")]
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("InformacaoSuporte")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("InformacaoSuporte")]
        public virtual LinhaProduto LinhaProduto { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("InformacaoSuporte")]
        public virtual Produto Produto { get; set; }
    }
}