// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class InstitutoSuperior
    {
        public InstitutoSuperior()
        {
            Faculdade = new HashSet<Faculdade>();
        }

        [StringLength(50)]
        public string IdInstituto { get; set; }
        [StringLength(500)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodInstitutoSuperior { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("InstitutoSuperior")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("InstitutoSuperior")]
        public virtual ICollection<Faculdade> Faculdade { get; set; }
    }
}