// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class LicencaModulo
    {
        public LicencaModulo()
        {
            LicencaModuloUser = new HashSet<LicencaModuloUser>();
        }

        [StringLength(50)]
        public string IdLicencaModulo { get; set; }
        [StringLength(100)]
        public string NumLicencaAtribuido { get; set; }
        public bool? NumLicensaUtilizado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataInicio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataVencimento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("ModuloCoreID")]
        [StringLength(50)]
        public string ModuloCoreId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("LicencaModulo")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("ModuloCoreId")]
        [InverseProperty("LicencaModulo")]
        public virtual ModuloCore ModuloCore { get; set; }
        [InverseProperty("LicencaModulo")]
        public virtual ICollection<LicencaModuloUser> LicencaModuloUser { get; set; }
    }
}