// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class LimiteCobertura
    {
        [StringLength(50)]
        public string IdLimiteCobertura { get; set; }
        [StringLength(2000)]
        public string Designacao { get; set; }
        public double? ValorBase { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataHoraUltimaRevisao { get; set; }
        public bool? ExtencaoLimitePadrao { get; set; }
        [Column("CoberturaProdutoID")]
        [StringLength(50)]
        public string CoberturaProdutoId { get; set; }
        public int? QuantidadeLimite { get; set; }
        [StringLength(10)]
        public string CodLimiteCobertura { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("CoberturaProdutoId")]
        [InverseProperty("LimiteCobertura")]
        public virtual Cobertura CoberturaProduto { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("LimiteCobertura")]
        public virtual Estado Estado { get; set; }
    }
}