// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class LimitesComissionamento
    {
        [StringLength(50)]
        public string IdLimitesComissionamento { get; set; }
        public double? ValorMin { get; set; }
        public double? ValorMax { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(10)]
        public string CodLimitesComissionamento { get; set; }
        public double? Percentagem { get; set; }
        public double? TaxaPlano { get; set; }
        public double? TaxaAtribuir { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("LimitesComissionamento")]
        public virtual Estado Estado { get; set; }
    }
}