// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class LimiteComissionamentoPlano
    {
        [StringLength(50)]
        public string IdLimiteComissionamentoPlano { get; set; }
        public double? PremioMin { get; set; }
        public double? PremioMax { get; set; }
        [StringLength(50)]
        public string ProvinciaPlanoId { get; set; }
        [StringLength(50)]
        public string CanalPlanoId { get; set; }
        [StringLength(50)]
        public string TipoSegmentoPlanoId { get; set; }
        [StringLength(50)]
        public string SectorActividadePlanoId { get; set; }
        [StringLength(50)]
        public string FidelizacaoPlanoId { get; set; }
        [StringLength(50)]
        public string SectorActividadePlano { get; set; }
        public double? TaxaPercentagem { get; set; }
        public double? TaxaMin { get; set; }
        public double? TaxaMax { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCricao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("CanalPlanoId")]
        [InverseProperty("LimiteComissionamentoPlano")]
        public virtual CanalPlano CanalPlano { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("LimiteComissionamentoPlano")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FidelizacaoPlanoId")]
        [InverseProperty("LimiteComissionamentoPlano")]
        public virtual FidelizacaoPlano FidelizacaoPlano { get; set; }
        [ForeignKey("ProvinciaPlanoId")]
        [InverseProperty("LimiteComissionamentoPlano")]
        public virtual ProvinciaPlano ProvinciaPlano { get; set; }
        [ForeignKey("SectorActividadePlanoId")]
        [InverseProperty("LimiteComissionamentoPlanoSectorActividadePlano1")]
        public virtual SectorActividadePlano SectorActividadePlano1 { get; set; }
        [ForeignKey("SectorActividadePlano")]
        [InverseProperty("LimiteComissionamentoPlanoSectorActividadePlanoNavigation")]
        public virtual SectorActividadePlano SectorActividadePlanoNavigation { get; set; }
        [ForeignKey("TipoSegmentoPlanoId")]
        [InverseProperty("LimiteComissionamentoPlano")]
        public virtual TipoSegmentoPlano TipoSegmentoPlano { get; set; }
    }
}