// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class LocalizacaoPneu
    {
        public LocalizacaoPneu()
        {
            Pneu = new HashSet<Pneu>();
        }

        [StringLength(50)]
        public string IdLocalizacaoPneu { get; set; }
        [StringLength(200)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodLocalizacaoPneu { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("LocalizacaoPneu")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("LocalizacaoPneu")]
        public virtual ICollection<Pneu> Pneu { get; set; }
    }
}