// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class LocaisEncargo
    {
        [StringLength(50)]
        public string IdLocaisEncargo { get; set; }
        [Column("RegiaoID")]
        [StringLength(50)]
        public string RegiaoId { get; set; }
        [Column("PaisID")]
        [StringLength(50)]
        public string PaisId { get; set; }
        [Column("ProvinciaID")]
        [StringLength(50)]
        public string ProvinciaId { get; set; }
        [Column("MunicipioID")]
        [StringLength(50)]
        public string MunicipioId { get; set; }
        [Column("DistritoID")]
        [StringLength(50)]
        public string DistritoId { get; set; }
        [Column("NivelAbrangenciaID")]
        [StringLength(50)]
        public string NivelAbrangenciaId { get; set; }
        [Column("EncargoID")]
        [StringLength(50)]
        public string EncargoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("DistritoId")]
        [InverseProperty("LocaisEncargo")]
        public virtual Distrito Distrito { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("LocaisEncargo")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MunicipioId")]
        [InverseProperty("LocaisEncargo")]
        public virtual Municipio Municipio { get; set; }
        [ForeignKey("NivelAbrangenciaId")]
        [InverseProperty("LocaisEncargo")]
        public virtual NivelAbrangencia NivelAbrangencia { get; set; }
        [ForeignKey("PaisId")]
        [InverseProperty("LocaisEncargo")]
        public virtual Pais Pais { get; set; }
        [ForeignKey("ProvinciaId")]
        [InverseProperty("LocaisEncargo")]
        public virtual Provincia Provincia { get; set; }
        [ForeignKey("RegiaoId")]
        [InverseProperty("LocaisEncargo")]
        public virtual Regiao Regiao { get; set; }
    }
}