// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class LocaisComissao
    {
        [StringLength(50)]
        public string IdLocaisComissao { get; set; }
        [Column("NivelAbrangenciaID")]
        [StringLength(50)]
        public string NivelAbrangenciaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string LocalComissao { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("LocaisComissao")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LocalComissao")]
        [InverseProperty("LocaisComissao")]
        public virtual Endereco LocalComissaoNavigation { get; set; }
        [ForeignKey("NivelAbrangenciaId")]
        [InverseProperty("LocaisComissao")]
        public virtual NivelAbrangencia NivelAbrangencia { get; set; }
    }
}