// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class MarcaAutomovel
    {
        public MarcaAutomovel()
        {
            ModeloAutomovel = new HashSet<ModeloAutomovel>();
            Sinistro = new HashSet<Sinistro>();
        }

        [StringLength(50)]
        public string IdMarcaAutomovel { get; set; }
        [StringLength(100)]
        public string Marca { get; set; }
        [StringLength(500)]
        public string CaminhoImagem { get; set; }
        [StringLength(10)]
        public string CodMarcaAutomovel { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("MarcaAutomovel")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("MarcaAutomovel")]
        public virtual ICollection<ModeloAutomovel> ModeloAutomovel { get; set; }
        [InverseProperty("MarcaAutomovel")]
        public virtual ICollection<Sinistro> Sinistro { get; set; }
    }
}