// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    [Table("MarcaGPS")]
    public partial class MarcaGps
    {
        public MarcaGps()
        {
            ModeloGps = new HashSet<ModeloGps>();
        }

        [Column("IdMarcaGPS")]
        [StringLength(50)]
        public string IdMarcaGps { get; set; }
        [StringLength(500)]
        public string Designacao { get; set; }
        [Column("CodMarcaGPS")]
        [StringLength(10)]
        public string CodMarcaGps { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("MarcaGps")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("MarcaGps")]
        public virtual ICollection<ModeloGps> ModeloGps { get; set; }
    }
}