// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class MediacaoComissao
    {
        [StringLength(50)]
        public string IdMediacaoComissao { get; set; }
        [StringLength(50)]
        public string CodMediacaoComissao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        public double? Angariacao { get; set; }
        public double? Cobranca { get; set; }
        public double? Total { get; set; }
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [StringLength(50)]
        public string TipoContratoId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("MediacaoComissao")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("MediacaoComissao")]
        public virtual LinhaProduto LinhaProduto { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("MediacaoComissao")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("TipoContratoId")]
        [InverseProperty("MediacaoComissao")]
        public virtual TipoContrato TipoContrato { get; set; }
    }
}