// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    [Table("MembroCAD")]
    public partial class MembroCad
    {
        [Column("IdMembroCAD")]
        [StringLength(50)]
        public string IdMembroCad { get; set; }
        [Column("DireccaoID")]
        [StringLength(50)]
        public string DireccaoId { get; set; }
        [Column("MembroID")]
        [StringLength(50)]
        public string MembroId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("DireccaoId")]
        [InverseProperty("MembroCad")]
        public virtual Direccao Direccao { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("MembroCad")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MembroId")]
        [InverseProperty("MembroCad")]
        public virtual Funcionario Membro { get; set; }
    }
}