// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class MetricasProduto
    {
        [StringLength(50)]
        public string IdMetricasProduto { get; set; }
        [Column("MetricaKpiID")]
        [StringLength(50)]
        public string MetricaKpiId { get; set; }
        [Column("ProdutoID")]
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [StringLength(50)]
        public string CodMetricasProduto { get; set; }

        [ForeignKey("MetricaKpiId")]
        [InverseProperty("MetricasProduto")]
        public virtual MetricaKpi MetricaKpi { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("MetricasProduto")]
        public virtual Produto Produto { get; set; }
    }
}