// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    [Table("ModeloGPS")]
    public partial class ModeloGps
    {
        public ModeloGps()
        {
            Gpsautomovel = new HashSet<Gpsautomovel>();
        }

        [Column("IdModeloGPS")]
        [StringLength(50)]
        public string IdModeloGps { get; set; }
        [StringLength(500)]
        public string Designacao { get; set; }
        [Column("MarcaGpsID")]
        [StringLength(50)]
        public string MarcaGpsId { get; set; }
        [Column("CodModeloGPS")]
        [StringLength(10)]
        public string CodModeloGps { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ModeloGps")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MarcaGpsId")]
        [InverseProperty("ModeloGps")]
        public virtual MarcaGps MarcaGps { get; set; }
        [InverseProperty("ModeloGps")]
        public virtual ICollection<Gpsautomovel> Gpsautomovel { get; set; }
    }
}