// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Morada
    {
        [StringLength(50)]
        public string IdMorada { get; set; }
        [StringLength(50)]
        public string CodMorada { get; set; }
        public int? NumCasa { get; set; }
        [StringLength(50)]
        public string CaixaPostal { get; set; }
        [StringLength(50)]
        public string NumAndar { get; set; }
        public int? Latitude { get; set; }
        [StringLength(50)]
        public string PontoReferencia { get; set; }
        [StringLength(50)]
        public string EnderecoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EnderecoId")]
        [InverseProperty("Morada")]
        public virtual Endereco Endereco { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Morada")]
        public virtual Estado Estado { get; set; }
    }
}