// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class NacionalidadePessoa
    {
        public NacionalidadePessoa()
        {
            NacionalidadePessoaPlano = new HashSet<NacionalidadePessoaPlano>();
        }

        [StringLength(50)]
        public string IdNacionalidadePessoa { get; set; }
        public bool? Principal { get; set; }
        [Column("NacionalidadeID")]
        [StringLength(50)]
        public string NacionalidadeId { get; set; }
        [Column("PessoaID")]
        [StringLength(50)]
        public string PessoaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodNacionalidadePessoa { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("NacionalidadePessoa")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("NacionalidadeId")]
        [InverseProperty("NacionalidadePessoa")]
        public virtual Pais Nacionalidade { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("NacionalidadePessoa")]
        public virtual Pessoa Pessoa { get; set; }
        [InverseProperty("NacionalidadePessoa")]
        public virtual ICollection<NacionalidadePessoaPlano> NacionalidadePessoaPlano { get; set; }
    }
}