// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Newsletter
    {
        [StringLength(50)]
        public string IdNewsletter { get; set; }
        [StringLength(100)]
        public string NomeCompleto { get; set; }
        [Column("EnderecoID")]
        [StringLength(50)]
        public string EnderecoId { get; set; }
        [Column("ContactoID")]
        [StringLength(50)]
        public string ContactoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("ContactoId")]
        [InverseProperty("Newsletter")]
        public virtual Contacto Contacto { get; set; }
        [ForeignKey("EnderecoId")]
        [InverseProperty("Newsletter")]
        public virtual Endereco Endereco { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Newsletter")]
        public virtual Estado Estado { get; set; }
    }
}