// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class NivelCompetencia
    {
        [StringLength(50)]
        public string IdNivelCompetencia { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string CodNivelCompetencia { get; set; }
        [StringLength(50)]
        public string PessoaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string FormaPagamentoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("NivelCompetencia")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FormaPagamentoId")]
        [InverseProperty("NivelCompetencia")]
        public virtual FormaPagamento FormaPagamento { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("NivelCompetencia")]
        public virtual Pessoa Pessoa { get; set; }
    }
}