// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ObjectoSegurado
    {
        public ObjectoSegurado()
        {
            CaracteristicaObjecto = new HashSet<CaracteristicaObjecto>();
            CoberturaSelecionada = new HashSet<CoberturaSelecionada>();
        }

        [StringLength(50)]
        public string IdObjectoSegurado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CotacaoId { get; set; }
        [StringLength(50)]
        public string ClassificacaoId { get; set; }
        [StringLength(50)]
        public string AutomovelId { get; set; }

        [ForeignKey("AutomovelId")]
        [InverseProperty("ObjectoSegurado")]
        public virtual Automovel Automovel { get; set; }
        [ForeignKey("ClassificacaoId")]
        [InverseProperty("ObjectoSegurado")]
        public virtual Classificacao Classificacao { get; set; }
        [ForeignKey("CotacaoId")]
        [InverseProperty("ObjectoSegurado")]
        public virtual Cotacao Cotacao { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("ObjectoSegurado")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("Objecto")]
        public virtual ICollection<CaracteristicaObjecto> CaracteristicaObjecto { get; set; }
        [InverseProperty("ObjectoSegurado")]
        public virtual ICollection<CoberturaSelecionada> CoberturaSelecionada { get; set; }
    }
}