// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ObrigacoesProduto
    {
        [StringLength(50)]
        public string IdObrigacoesProduto { get; set; }
        public int? NumPonto { get; set; }
        [StringLength(4000)]
        public string Designacao { get; set; }
        [Column("ProdutoID")]
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [Column("ResponsavelObrigacoesID")]
        [StringLength(50)]
        public string ResponsavelObrigacoesId { get; set; }
        [Column("TipoObrigacoesID")]
        [StringLength(50)]
        public string TipoObrigacoesId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("LinhaProdutoID")]
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodObrigacoesProduto { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ObrigacoesProduto")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("ObrigacoesProduto")]
        public virtual LinhaProduto LinhaProduto { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("ObrigacoesProduto")]
        public virtual Produto Produto { get; set; }
        [ForeignKey("ResponsavelObrigacoesId")]
        [InverseProperty("ObrigacoesProduto")]
        public virtual ResponsavelObrigacoes ResponsavelObrigacoes { get; set; }
        [ForeignKey("TipoObrigacoesId")]
        [InverseProperty("ObrigacoesProduto")]
        public virtual TipoObrigacoes TipoObrigacoes { get; set; }
    }
}