// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class OfertaLinha
    {
        [StringLength(50)]
        public string IdOfertaLina { get; set; }
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [StringLength(50)]
        public string HistoricoOfertaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodOfertaLinha { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("OfertaLinha")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("HistoricoOfertaId")]
        [InverseProperty("OfertaLinha")]
        public virtual HistoricoOferta HistoricoOferta { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("OfertaLinha")]
        public virtual LinhaProduto LinhaProduto { get; set; }
    }
}