// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Operacao
    {
        public Operacao()
        {
            ComissaoPlano = new HashSet<ComissaoPlano>();
            Movimento = new HashSet<Movimento>();
            OperacaoPlano = new HashSet<OperacaoPlano>();
        }

        [StringLength(50)]
        public string IdOperacao { get; set; }
        [Required]
        [StringLength(50)]
        public string CodOperacao { get; set; }
        [StringLength(200)]
        public string Designacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string SubContaId { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        [StringLength(50)]
        public string ClassificacaoOperacaoId { get; set; }
        public double? Valor { get; set; }
        [StringLength(50)]
        public string NaturezaMovimentoId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string TipoOperacaoId { get; set; }

        [ForeignKey("ClassificacaoOperacaoId")]
        [InverseProperty("Operacao")]
        public virtual ClassificacaoOperacao ClassificacaoOperacao { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Operacao")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("Operacao")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("Operacao")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("SubContaId")]
        [InverseProperty("Operacao")]
        public virtual PlanoContas SubConta { get; set; }
        [ForeignKey("TipoOperacaoId")]
        [InverseProperty("Operacao")]
        public virtual TipoOperacao TipoOperacao { get; set; }
        [InverseProperty("Operacao")]
        public virtual CondicaoOperacao CondicaoOperacao { get; set; }
        [InverseProperty("Operacao")]
        public virtual ICollection<ComissaoPlano> ComissaoPlano { get; set; }
        public virtual ICollection<Movimento> Movimento { get; set; }
        [InverseProperty("Operacao")]
        public virtual ICollection<OperacaoPlano> OperacaoPlano { get; set; }
    }
}