// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class OutrosSeguros
    {
        public OutrosSeguros()
        {
            BoletimAdesaoSaude = new HashSet<BoletimAdesaoSaude>();
        }

        [StringLength(50)]
        public string IdOutrosSeguros { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string OutraSeguradora { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        public int? NumeroApolice { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("OutrosSeguros")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("OutrosSeguros")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [InverseProperty("OutrosSeguros")]
        public virtual ICollection<BoletimAdesaoSaude> BoletimAdesaoSaude { get; set; }
    }
}