// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class PadraoRecorrencia
    {
        public PadraoRecorrencia()
        {
            RecorrenciaDiario = new HashSet<RecorrenciaDiario>();
            RecorrenciaMesAno = new HashSet<RecorrenciaMesAno>();
            RecorrenciaSemanal = new HashSet<RecorrenciaSemanal>();
            TarefaRecorrente = new HashSet<TarefaRecorrente>();
        }

        [StringLength(50)]
        public string IdPadraoRecorrencia { get; set; }
        [StringLength(50)]
        public string Descricao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("IntervaloRecorrenciaID")]
        [StringLength(50)]
        public string IntervaloRecorrenciaId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("PadraoRecorrencia")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("IntervaloRecorrenciaId")]
        [InverseProperty("PadraoRecorrencia")]
        public virtual IntervaloRecorrencia IntervaloRecorrencia { get; set; }
        [InverseProperty("PadraoRecorrencia")]
        public virtual ICollection<RecorrenciaDiario> RecorrenciaDiario { get; set; }
        [InverseProperty("PadraoRecorrencia")]
        public virtual ICollection<RecorrenciaMesAno> RecorrenciaMesAno { get; set; }
        [InverseProperty("PadraoRecorrencia")]
        public virtual ICollection<RecorrenciaSemanal> RecorrenciaSemanal { get; set; }
        [InverseProperty("PadraoRecorrencia")]
        public virtual ICollection<TarefaRecorrente> TarefaRecorrente { get; set; }
    }
}