// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class PapelPessoaResseguro
    {
        [StringLength(50)]
        public string IdPapelPessoaResseguro { get; set; }
        [StringLength(50)]
        public string SubscricaoCessaoRetencao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(10)]
        public string CodPapelPessoaResseguro { get; set; }
        [StringLength(50)]
        public string IdPessoaRetente { get; set; }
        [StringLength(50)]
        public string IdPessoCedente { get; set; }

        [ForeignKey("IdPessoCedente")]
        [InverseProperty("PapelPessoaResseguroIdPessoCedenteNavigation")]
        public virtual PapelPessoa IdPessoCedenteNavigation { get; set; }
        [ForeignKey("IdPessoaRetente")]
        [InverseProperty("PapelPessoaResseguroIdPessoaRetenteNavigation")]
        public virtual PapelPessoa IdPessoaRetenteNavigation { get; set; }
        [ForeignKey("SubscricaoCessaoRetencao")]
        [InverseProperty("PapelPessoaResseguro")]
        public virtual SubscricaoCessaoRetencao SubscricaoCessaoRetencaoNavigation { get; set; }
    }
}