// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class PapelDesconto
    {
        [StringLength(50)]
        public string IdPapelDesconto { get; set; }
        [StringLength(50)]
        public string PapelId { get; set; }
        [StringLength(50)]
        public string DescontoId { get; set; }

        [ForeignKey("DescontoId")]
        [InverseProperty("PapelDesconto")]
        public virtual Desconto Desconto { get; set; }
        [ForeignKey("PapelId")]
        [InverseProperty("PapelDesconto")]
        public virtual Papel Papel { get; set; }
    }
}