// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Perda
    {
        public Perda()
        {
            Reclamacao = new HashSet<Reclamacao>();
            Reparacao = new HashSet<Reparacao>();
        }

        [StringLength(50)]
        public string IdPerda { get; set; }
        [StringLength(500)]
        public string Designacao { get; set; }
        public bool? PerdaCoberta { get; set; }
        public double? PossivelValorMonetario { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataOcorrencia { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataDescoberta { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataNotificacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataInicioReparacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataFimReparacao { get; set; }
        [StringLength(1000)]
        public string CausaPerda { get; set; }
        [StringLength(1000)]
        public string Consequencias { get; set; }
        [StringLength(500)]
        public string VideoImagem { get; set; }
        [Column("SubContaID")]
        [StringLength(50)]
        public string SubContaId { get; set; }
        public double PercentagemResponsabilidade { get; set; }
        [Column("TipoPerdaID")]
        [StringLength(50)]
        public string TipoPerdaId { get; set; }
        [Column("CircunstanciaPerdaID")]
        [StringLength(50)]
        public string CircunstanciaPerdaId { get; set; }
        [Column("PacienteID")]
        [StringLength(50)]
        public string PacienteId { get; set; }
        [Column("CustoID")]
        [StringLength(50)]
        public string CustoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Required]
        public bool? IsTaxa { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [StringLength(50)]
        public string NaturezaMovimentoId { get; set; }
        [Required]
        public bool? Contabiliza { get; set; }

        [ForeignKey("CircunstanciaPerdaId")]
        [InverseProperty("Perda")]
        public virtual CircunstanciaPerda CircunstanciaPerda { get; set; }
        [ForeignKey("CustoId")]
        [InverseProperty("Perda")]
        public virtual Custo Custo { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Perda")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("NaturezaMovimentoId")]
        [InverseProperty("Perda")]
        public virtual NaturezaMovimento NaturezaMovimento { get; set; }
        [ForeignKey("PacienteId")]
        [InverseProperty("Perda")]
        public virtual Paciente Paciente { get; set; }
        [ForeignKey("SubContaId")]
        [InverseProperty("Perda")]
        public virtual PlanoContas SubConta { get; set; }
        [ForeignKey("TipoPerdaId")]
        [InverseProperty("Perda")]
        public virtual TipoPerda TipoPerda { get; set; }
        [InverseProperty("Perda")]
        public virtual ICollection<Reclamacao> Reclamacao { get; set; }
        [InverseProperty("Perda")]
        public virtual ICollection<Reparacao> Reparacao { get; set; }
    }
}