// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class PerguntasFrequentesProduto
    {
        [StringLength(50)]
        public string IdPerguntasFrequentesProduto { get; set; }
        [Column(TypeName = "ntext")]
        public string Perguntas { get; set; }
        [Column(TypeName = "ntext")]
        public string Resposta { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [StringLength(50)]
        public string CodPerguntasFrequentesProduto { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("PerguntasFrequentesProduto")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("PerguntasFrequentesProduto")]
        public virtual Produto Produto { get; set; }
    }
}