// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Periodo
    {
        [StringLength(50)]
        public string IdPeriodo { get; set; }
        public int? Ano { get; set; }
        public bool? Estado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string CodPeriodo { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string ExercicioId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("Periodo")]
        public virtual Estado EstadoNavigation { get; set; }
        [ForeignKey("ExercicioId")]
        [InverseProperty("Periodo")]
        public virtual Exercicio Exercicio { get; set; }
    }
}