// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Perspicacia
    {
        [StringLength(50)]
        public string IdVantagensProdutos { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [Column(TypeName = "ntext")]
        public string Descricao { get; set; }
        [Column("caminhoIcone")]
        [StringLength(100)]
        public string CaminhoIcone { get; set; }
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string CodPerspicacia { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("Perspicacia")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("Perspicacia")]
        public virtual Produto Produto { get; set; }
    }
}