// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class PlanoComercialPorProdutor
    {
        [StringLength(50)]
        public string IdPlanoComercialPorProdutor { get; set; }
        public double? ValorBalcao { get; set; }
        public int? QtdPropostaVenda { get; set; }
        [StringLength(50)]
        public string CodPlanoComercialPorProdutor { get; set; }
        [StringLength(50)]
        public string ProdutorId { get; set; }
        [StringLength(50)]
        public string BalcaoPlanoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("BalcaoPlanoId")]
        [InverseProperty("PlanoComercialPorProdutor")]
        public virtual BalcaoPlano BalcaoPlano { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("PlanoComercialPorProdutor")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("ProdutorId")]
        [InverseProperty("PlanoComercialPorProdutor")]
        public virtual Pessoa Produtor { get; set; }
    }
}