// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    [Table("POS")]
    public partial class Pos
    {
        public Pos()
        {
            ContaBancariaPos = new HashSet<ContaBancariaPos>();
            InformacaoBancariaPos = new HashSet<InformacaoBancariaPos>();
            PessoasPos = new HashSet<PessoasPos>();
        }

        [Column("IdPOS")]
        [StringLength(50)]
        public string IdPos { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [Column("CodPOS")]
        [StringLength(50)]
        public string CodPos { get; set; }
        [Column("NumPOS")]
        [StringLength(50)]
        public string NumPos { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("Pos")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("Pos")]
        public virtual ICollection<ContaBancariaPos> ContaBancariaPos { get; set; }
        [InverseProperty("Pos")]
        public virtual ICollection<InformacaoBancariaPos> InformacaoBancariaPos { get; set; }
        [InverseProperty("Pos")]
        public virtual ICollection<PessoasPos> PessoasPos { get; set; }
    }
}