// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class PrecarioProduto
    {
        public PrecarioProduto()
        {
            ImpostoPrecario = new HashSet<ImpostoPrecario>();
            LinhaProdutoImposto = new HashSet<LinhaProdutoImposto>();
            TipoTarifa = new HashSet<TipoTarifa>();
        }

        [StringLength(50)]
        public string IdPrecarioProduto { get; set; }
        public double? PrecoBase { get; set; }
        public int? QtdDiaMin { get; set; }
        public int? QtdDiaMax { get; set; }
        [StringLength(100)]
        public string Descricao { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string CanalId { get; set; }
        public double CustoApolice { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCancelamento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataEstorno { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAnulacao { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string TaxasId { get; set; }
        [StringLength(50)]
        public string TipoOperacaoId { get; set; }

        [ForeignKey("CanalId")]
        [InverseProperty("PrecarioProduto")]
        public virtual Canal Canal { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("PrecarioProduto")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("PrecarioProduto")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("PrecarioProduto")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("TaxasId")]
        [InverseProperty("PrecarioProduto")]
        public virtual Taxas Taxas { get; set; }
        [ForeignKey("TipoOperacaoId")]
        [InverseProperty("PrecarioProduto")]
        public virtual TipoOperacao TipoOperacao { get; set; }
        [InverseProperty("PrecarioProduto")]
        public virtual ICollection<ImpostoPrecario> ImpostoPrecario { get; set; }
        [InverseProperty("PrecarioProduto")]
        public virtual ICollection<LinhaProdutoImposto> LinhaProdutoImposto { get; set; }
        [InverseProperty("PrecarioProduto")]
        public virtual ICollection<TipoTarifa> TipoTarifa { get; set; }
    }
}