// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class PrecosMedicamentos
    {
        [StringLength(50)]
        public string IdPrecarioMedicamentos { get; set; }
        public int? Unidade { get; set; }
        public int? Minimo { get; set; }
        [StringLength(50)]
        public string IdPessoa { get; set; }
        [StringLength(50)]
        public string IdMedicamento { get; set; }
        [StringLength(50)]
        public string Valor { get; set; }
        [StringLength(50)]
        public string IdMoeda { get; set; }
        [Column("PvPaOA")]
        [StringLength(50)]
        public string PvPaOa { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string CodPrecosMedicamentos { get; set; }

        [ForeignKey("IdMedicamento")]
        [InverseProperty("PrecosMedicamentos")]
        public virtual Medicamentos IdMedicamentoNavigation { get; set; }
        [ForeignKey("IdMoeda")]
        [InverseProperty("PrecosMedicamentos")]
        public virtual Moeda IdMoedaNavigation { get; set; }
        [ForeignKey("IdPessoa")]
        [InverseProperty("PrecosMedicamentos")]
        public virtual Pessoa IdPessoaNavigation { get; set; }
    }
}