// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class PremiosMinimos
    {
        [StringLength(50)]
        public string IdPremiosMinimos { get; set; }
        public int? Duracao { get; set; }
        public double? PremioMinimo { get; set; }
        [StringLength(300)]
        public string DescricaoPremio { get; set; }
        [Column("MoedaID")]
        [StringLength(50)]
        public string MoedaId { get; set; }
        [Column("ProdutoID")]
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [StringLength(10)]
        public string CodPremiosMinimos { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("LinhaProdutoID")]
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("PremiosMinimos")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("PremiosMinimos")]
        public virtual LinhaProduto LinhaProduto { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("PremiosMinimos")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("PremiosMinimos")]
        public virtual Produto Produto { get; set; }
    }
}