// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class PrestacoesFraccionamento
    {
        [StringLength(50)]
        public string IdPrestacao { get; set; }
        public int? NumPrestacao { get; set; }
        public double Percentagem { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodPrestacoesFraccionamento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Required]
        public bool? IsTaxa { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string FraccionamentoProdutoId { get; set; }
        public double? PremioMinimoAnual { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("PrestacoesFraccionamento")]
        public virtual Estado Estado { get; set; }
    }
}