// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Questionario
    {
        public Questionario()
        {
            ObjectoEnvolvido = new HashSet<ObjectoEnvolvido>();
            RespostaPergunta = new HashSet<RespostaPergunta>();
        }

        [StringLength(50)]
        public string IdQuestionario { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CotacaoId { get; set; }
        [StringLength(50)]
        public string PessoaId { get; set; }
        [StringLength(50)]
        public string Descricao { get; set; }

        [ForeignKey("CotacaoId")]
        [InverseProperty("Questionario")]
        public virtual Cotacao Cotacao { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Questionario")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("Questionario")]
        public virtual Pessoa Pessoa { get; set; }
        [InverseProperty("Questionario")]
        public virtual ICollection<ObjectoEnvolvido> ObjectoEnvolvido { get; set; }
        [InverseProperty("Questionario")]
        public virtual ICollection<RespostaPergunta> RespostaPergunta { get; set; }
    }
}