// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class RamoQualidadeSegura
    {
        [StringLength(50)]
        public string IdRamoQualidadeSegura { get; set; }
        [StringLength(50)]
        public string RamoSeguroId { get; set; }
        [StringLength(50)]
        public string CodRamoQualidadeSegura { get; set; }
        [StringLength(50)]
        public string QualidadeSeguraId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [ForeignKey("QualidadeSeguraId")]
        [InverseProperty("RamoQualidadeSegura")]
        public virtual QualidadeSegura QualidadeSegura { get; set; }
        [ForeignKey("RamoSeguroId")]
        [InverseProperty("RamoQualidadeSegura")]
        public virtual TipoRamoSeguro RamoSeguro { get; set; }
    }
}