// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class RapelProdutor
    {
        public RapelProdutor()
        {
            PapelProdutor = new HashSet<PapelProdutor>();
        }

        [StringLength(50)]
        public string IdRapelProdutor { get; set; }
        [StringLength(50)]
        public string CodRapelProdutor { get; set; }
        [StringLength(50)]
        public string PessoaId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string TipoRamoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        public double? ValorMin { get; set; }
        public double? ValorMax { get; set; }
        [StringLength(50)]
        public string LimitesRapelId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("RapelProdutor")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LimitesRapelId")]
        [InverseProperty("RapelProdutor")]
        public virtual LimitesRapel LimitesRapel { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("RapelProdutor")]
        public virtual Pessoa Pessoa { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("RapelProdutor")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("TipoRamoId")]
        [InverseProperty("RapelProdutor")]
        public virtual TipoRamoSeguro TipoRamo { get; set; }
        [InverseProperty("RapelProdutor")]
        public virtual ICollection<PapelProdutor> PapelProdutor { get; set; }
    }
}