// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class RedeSociais
    {
        public RedeSociais()
        {
            RedeSocialPessoa = new HashSet<RedeSocialPessoa>();
        }

        [StringLength(50)]
        public string IdRedeSociais { get; set; }
        [StringLength(500)]
        public string LinkRedeSocial { get; set; }
        [Column("ContactoID")]
        [StringLength(50)]
        public string ContactoId { get; set; }
        [Column("TipoRedeSociaisID")]
        [StringLength(50)]
        public string TipoRedeSociaisId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("ContactoId")]
        [InverseProperty("RedeSociais")]
        public virtual Contacto Contacto { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("RedeSociais")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("TipoRedeSociaisId")]
        [InverseProperty("RedeSociais")]
        public virtual TipoRedeSociais TipoRedeSociais { get; set; }
        [InverseProperty("RedeSocial")]
        public virtual ICollection<RedeSocialPessoa> RedeSocialPessoa { get; set; }
    }
}