// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ReivindicacoesFeitasApolice
    {
        [StringLength(50)]
        public string IdReivindicacoesFeitasApolice { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataHoraEmissao { get; set; }
        public double PercentagemDescobertura { get; set; }
        public double? MontanteDescoberta { get; set; }
        [Column("ApoliceID")]
        [StringLength(50)]
        public string ApoliceId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Required]
        public bool? IsTaxa { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("ApoliceId")]
        [InverseProperty("ReivindicacoesFeitasApolice")]
        public virtual Apolice Apolice { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("ReivindicacoesFeitasApolice")]
        public virtual Estado Estado { get; set; }
    }
}