// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class RelatorioProduto
    {
        [StringLength(50)]
        public string IdRelatorioProduto { get; set; }
        [Required]
        [StringLength(50)]
        public string RelatorioId { get; set; }
        public string LinhaId { get; set; }
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [StringLength(50)]
        public string CodRelatorioProduto { get; set; }

        [ForeignKey("ProdutoId")]
        [InverseProperty("RelatorioProduto")]
        public virtual Produto Produto { get; set; }
        [ForeignKey("RelatorioId")]
        [InverseProperty("RelatorioProduto")]
        public virtual Relatorio Relatorio { get; set; }
    }
}