// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Resseguro
    {
        public Resseguro()
        {
            CoberturaResseguro = new HashSet<CoberturaResseguro>();
            ComissaoResseguro = new HashSet<ComissaoResseguro>();
            CondicoesReSeguro = new HashSet<CondicoesReSeguro>();
            ContratoResseguro = new HashSet<ContratoResseguro>();
            ExcessoPerda = new HashSet<ExcessoPerda>();
            SubscricaoCessaoRetencao = new HashSet<SubscricaoCessaoRetencao>();
        }

        [StringLength(50)]
        public string IdResseguro { get; set; }
        public double? CapitalSeguro { get; set; }
        public double? Premio { get; set; }
        [StringLength(50)]
        public string ResseguradorId { get; set; }
        [StringLength(50)]
        public string MediadorId { get; set; }
        [StringLength(50)]
        public string TipoResseguroId { get; set; }
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [StringLength(50)]
        public string SeguradoraDirectaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataInicio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataExpiracao { get; set; }
        public bool? IsTaxa { get; set; }
        [StringLength(50)]
        public string CodResseguro { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UltModificacaoPorId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string NotaId { get; set; }
        [StringLength(50)]
        public string TarefaId { get; set; }
        public double? ValorLiquido { get; set; }
        [StringLength(50)]
        public string SinistroId { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string FormaResseguroId { get; set; }
        [StringLength(50)]
        public string ContratoId { get; set; }
        public double? Cedencia { get; set; }
        public double? Comissao { get; set; }
        public double? Snistros { get; set; }

        [ForeignKey("SinistroId")]
        [InverseProperty("Resseguro")]
        public virtual Sinistro Sinistro { get; set; }
        [InverseProperty("Resseguro")]
        public virtual ICollection<CoberturaResseguro> CoberturaResseguro { get; set; }
        [InverseProperty("Resseguro")]
        public virtual ICollection<ComissaoResseguro> ComissaoResseguro { get; set; }
        [InverseProperty("Resseguro")]
        public virtual ICollection<CondicoesReSeguro> CondicoesReSeguro { get; set; }
        [InverseProperty("Resseguro")]
        public virtual ICollection<ContratoResseguro> ContratoResseguro { get; set; }
        [InverseProperty("Resseguro")]
        public virtual ICollection<ExcessoPerda> ExcessoPerda { get; set; }
        [InverseProperty("Resseguro")]
        public virtual ICollection<SubscricaoCessaoRetencao> SubscricaoCessaoRetencao { get; set; }
    }
}