// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class RestricoesCategoriasCartaConducao
    {
        public RestricoesCategoriasCartaConducao()
        {
            CartaConducao = new HashSet<CartaConducao>();
        }

        [StringLength(50)]
        public string IdRestricao { get; set; }
        [StringLength(5)]
        public string CodRestricoesCategoriasCartaConducao { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("RestricoesCategoriasCartaConducao")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("RestricoesCategoriasCartaConducao")]
        public virtual ICollection<CartaConducao> CartaConducao { get; set; }
    }
}