// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Seccao
    {
        public Seccao()
        {
            CentroCusto = new HashSet<CentroCusto>();
            CentroResponsabilidade = new HashSet<CentroResponsabilidade>();
            ChefeSeccao = new HashSet<ChefeSeccao>();
            Funcionario = new HashSet<Funcionario>();
            OperacoesCrudpessoa = new HashSet<OperacoesCrudpessoa>();
            PessoaTarefa = new HashSet<PessoaTarefa>();
            Posicao = new HashSet<Posicao>();
        }

        [StringLength(50)]
        public string IdSeccao { get; set; }
        [StringLength(100)]
        public string NomeSeccao { get; set; }
        [Column("ContactoID")]
        [StringLength(50)]
        public string ContactoId { get; set; }
        [Column("SectorID")]
        [StringLength(50)]
        public string SectorId { get; set; }
        [StringLength(10)]
        public string CodSeccao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [Column("SubContaID")]
        [StringLength(50)]
        public string SubContaId { get; set; }
        [Required]
        public bool? Contabiliza { get; set; }
        [StringLength(50)]
        public string CargoId { get; set; }
        [StringLength(50)]
        public string FuncaoId { get; set; }

        [ForeignKey("CargoId")]
        [InverseProperty("Seccao")]
        public virtual Cargo Cargo { get; set; }
        [ForeignKey("ContactoId")]
        [InverseProperty("Seccao")]
        public virtual Contacto Contacto { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Seccao")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FuncaoId")]
        [InverseProperty("Seccao")]
        public virtual Funcao Funcao { get; set; }
        [ForeignKey("SectorId")]
        [InverseProperty("Seccao")]
        public virtual Sector Sector { get; set; }
        [ForeignKey("SubContaId")]
        [InverseProperty("Seccao")]
        public virtual PlanoContas SubConta { get; set; }
        [InverseProperty("Seccao")]
        public virtual ICollection<CentroCusto> CentroCusto { get; set; }
        [InverseProperty("Seccao")]
        public virtual ICollection<CentroResponsabilidade> CentroResponsabilidade { get; set; }
        [InverseProperty("Seccao")]
        public virtual ICollection<ChefeSeccao> ChefeSeccao { get; set; }
        [InverseProperty("Seccao")]
        public virtual ICollection<Funcionario> Funcionario { get; set; }
        [InverseProperty("Seccao")]
        public virtual ICollection<OperacoesCrudpessoa> OperacoesCrudpessoa { get; set; }
        [InverseProperty("Seccao")]
        public virtual ICollection<PessoaTarefa> PessoaTarefa { get; set; }
        [InverseProperty("Seccao")]
        public virtual ICollection<Posicao> Posicao { get; set; }
    }
}