// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class SectorAtividadeEconomica
    {
        public SectorAtividadeEconomica()
        {
            Cae = new HashSet<Cae>();
            SectorActividadesProdutor = new HashSet<SectorActividadesProdutor>();
        }

        [StringLength(50)]
        public string IdSectorAtividadeEconomica { get; set; }
        [StringLength(100)]
        public string CodSectorAtividadeEconomica { get; set; }
        [StringLength(2048)]
        public string Designacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [StringLength(50)]
        public string TipoEntidadeId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("SectorAtividadeEconomica")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("TipoEntidadeId")]
        [InverseProperty("SectorAtividadeEconomica")]
        public virtual TipoEntidade TipoEntidade { get; set; }
        [InverseProperty("TituloCae")]
        public virtual ICollection<Cae> Cae { get; set; }
        [InverseProperty("SectorActividade")]
        public virtual ICollection<SectorActividadesProdutor> SectorActividadesProdutor { get; set; }
    }
}