// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class SectorActividadeComissionamento
    {
        [StringLength(50)]
        public string IdSectorActividadeComissionamento { get; set; }
        [StringLength(50)]
        public string CodSectorActividadeComissionamento { get; set; }
        [StringLength(50)]
        public string LimitesComissionamentoProdutorId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string SectorActividadeId { get; set; }
        [StringLength(50)]
        public string ComissionamentoId { get; set; }

        [ForeignKey("ComissionamentoId")]
        [InverseProperty("SectorActividadeComissionamento")]
        public virtual Comissionamento Comissionamento { get; set; }
        [ForeignKey("LimitesComissionamentoProdutorId")]
        [InverseProperty("SectorActividadeComissionamento")]
        public virtual LimiteComissionamentoProdutor LimitesComissionamentoProdutor { get; set; }
        [ForeignKey("SectorActividadeId")]
        [InverseProperty("SectorActividadeComissionamento")]
        public virtual SectorActividade SectorActividade { get; set; }
    }
}