// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class SegmentoProduto
    {
        public SegmentoProduto()
        {
            Comissionamento = new HashSet<Comissionamento>();
            SegmentoProdutoPlano = new HashSet<SegmentoProdutoPlano>();
        }

        [StringLength(50)]
        public string IdSegmentoProduto { get; set; }
        public int? IdadeMin { get; set; }
        public int? IdadeMax { get; set; }
        [StringLength(50)]
        public string SexoId { get; set; }
        [Column("BalcaoID")]
        [StringLength(50)]
        public string BalcaoId { get; set; }
        [Column("FidelizacaoID")]
        [StringLength(50)]
        public string FidelizacaoId { get; set; }
        [Column("TipoSegmentoID")]
        [StringLength(50)]
        public string TipoSegmentoId { get; set; }
        [Column("CAEid")]
        [StringLength(50)]
        public string Caeid { get; set; }
        [Column("PessoaID")]
        [StringLength(50)]
        public string PessoaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodSegmentoProduto { get; set; }
        [StringLength(50)]
        public string NaturezaMovimentoId { get; set; }
        [StringLength(50)]
        public string SubContaId { get; set; }
        [Column("PlanoProdutoID")]
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }

        [ForeignKey("BalcaoId")]
        [InverseProperty("SegmentoProduto")]
        public virtual Balcao Balcao { get; set; }
        [ForeignKey("Caeid")]
        [InverseProperty("SegmentoProduto")]
        public virtual Cae Cae { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("SegmentoProduto")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FidelizacaoId")]
        [InverseProperty("SegmentoProduto")]
        public virtual Fidelizacao Fidelizacao { get; set; }
        [ForeignKey("NaturezaMovimentoId")]
        [InverseProperty("SegmentoProduto")]
        public virtual NaturezaMovimento NaturezaMovimento { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("SegmentoProduto")]
        public virtual Pessoa Pessoa { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("SegmentoProduto")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("SexoId")]
        [InverseProperty("SegmentoProduto")]
        public virtual Sexo Sexo { get; set; }
        [ForeignKey("SubContaId")]
        [InverseProperty("SegmentoProduto")]
        public virtual PlanoContas SubConta { get; set; }
        [ForeignKey("TipoSegmentoId")]
        [InverseProperty("SegmentoProduto")]
        public virtual TipoSegmento TipoSegmento { get; set; }
        [InverseProperty("Segmento")]
        public virtual ICollection<Comissionamento> Comissionamento { get; set; }
        [InverseProperty("SegmentoProduto")]
        public virtual ICollection<SegmentoProdutoPlano> SegmentoProdutoPlano { get; set; }
    }
}