// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class SegmentoTipoCobertura
    {
        [StringLength(50)]
        public string IdSegmentoTipoCobertura { get; set; }
        public int? IdadeMin { get; set; }
        public int? IdadeMax { get; set; }
        [StringLength(50)]
        public string SexoId { get; set; }
        [Column("FidelizacaoID")]
        [StringLength(50)]
        public string FidelizacaoId { get; set; }
        [Column("CAEid")]
        [StringLength(50)]
        public string Caeid { get; set; }
        [Column("TipoSegmentoID")]
        [StringLength(50)]
        public string TipoSegmentoId { get; set; }
        [Column("TipoCoberturaID")]
        [StringLength(50)]
        public string TipoCoberturaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("Caeid")]
        [InverseProperty("SegmentoTipoCobertura")]
        public virtual Cae Cae { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("SegmentoTipoCobertura")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FidelizacaoId")]
        [InverseProperty("SegmentoTipoCobertura")]
        public virtual Fidelizacao Fidelizacao { get; set; }
        [ForeignKey("SexoId")]
        [InverseProperty("SegmentoTipoCobertura")]
        public virtual Sexo Sexo { get; set; }
        [ForeignKey("TipoCoberturaId")]
        [InverseProperty("SegmentoTipoCobertura")]
        public virtual TipoCobertura TipoCobertura { get; set; }
        [ForeignKey("TipoSegmentoId")]
        [InverseProperty("SegmentoTipoCobertura")]
        public virtual TipoSegmento TipoSegmento { get; set; }
    }
}