// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class SegmentoFranquia
    {
        [StringLength(50)]
        public string IdSegmentoFranquia { get; set; }
        [Column("SegmentoID")]
        [StringLength(50)]
        public string SegmentoId { get; set; }
        [Column("PessoaID")]
        [StringLength(50)]
        public string PessoaId { get; set; }
        [Column("CaeID")]
        [StringLength(50)]
        public string CaeId { get; set; }
        [Column("FranquiaID")]
        [StringLength(50)]
        public string FranquiaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("CaeId")]
        [InverseProperty("SegmentoFranquia")]
        public virtual Cae Cae { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("SegmentoFranquia")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FranquiaId")]
        [InverseProperty("SegmentoFranquia")]
        public virtual Franquia Franquia { get; set; }
        [ForeignKey("SegmentoId")]
        [InverseProperty("SegmentoFranquia")]
        public virtual TipoSegmento Segmento { get; set; }
    }
}