// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Servico
    {
        public Servico()
        {
            ServicoPlano = new HashSet<ServicoPlano>();
            ServicosAdicionais = new HashSet<ServicosAdicionais>();
            ServicosBase = new HashSet<ServicosBase>();
        }

        [StringLength(50)]
        public string IdServico { get; set; }
        [StringLength(2048)]
        public string Designacao { get; set; }
        [Column("TipoServicoID")]
        [StringLength(50)]
        public string TipoServicoId { get; set; }
        [StringLength(10)]
        public string CodServico { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        public double? Preco { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }
        [StringLength(50)]
        public string PrestadorServicoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("Servico")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("Servico")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("PrestadorServicoId")]
        [InverseProperty("Servico")]
        public virtual PrestadorServico PrestadorServico { get; set; }
        [ForeignKey("TipoServicoId")]
        [InverseProperty("Servico")]
        public virtual TipoServico TipoServico { get; set; }
        [InverseProperty("Servico")]
        public virtual ICollection<ServicoPlano> ServicoPlano { get; set; }
        [InverseProperty("Servico")]
        public virtual ICollection<ServicosAdicionais> ServicosAdicionais { get; set; }
        [InverseProperty("Servico")]
        public virtual ICollection<ServicosBase> ServicosBase { get; set; }
    }
}