// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ServicosAdicionais
    {
        [StringLength(50)]
        public string IdServicosAdicionais { get; set; }
        [Column("OBS")]
        [StringLength(2048)]
        public string Obs { get; set; }
        [Column("PlanoProdutoID")]
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(10)]
        public string CodServicosAdicionais { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("ServicoID")]
        [StringLength(50)]
        public string ServicoId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("CoberturaProdutoID")]
        [StringLength(50)]
        public string CoberturaProdutoId { get; set; }
        public double? Preco { get; set; }
        [StringLength(50)]
        public string MoedaId { get; set; }

        [ForeignKey("CoberturaProdutoId")]
        [InverseProperty("ServicosAdicionais")]
        public virtual Cobertura CoberturaProduto { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("ServicosAdicionais")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("ServicosAdicionais")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("ServicosAdicionais")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("ServicoId")]
        [InverseProperty("ServicosAdicionais")]
        public virtual Servico Servico { get; set; }
    }
}