// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class SimulacaoDependente
    {
        [StringLength(50)]
        public string IdSimulacaoDependente { get; set; }
        public int NumOrdem { get; set; }
        [StringLength(50)]
        public string CodSimulacaoDependente { get; set; }
        [StringLength(50)]
        public string SimulacaoId { get; set; }
        [StringLength(50)]
        public string CotacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("CotacaoId")]
        [InverseProperty("SimulacaoDependente")]
        public virtual Cotacao Cotacao { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("SimulacaoDependente")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("SimulacaoId")]
        [InverseProperty("SimulacaoDependente")]
        public virtual Simulacao Simulacao { get; set; }
    }
}