// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Sinistro
    {
        public Sinistro()
        {
            AutoridadesContactadas = new HashSet<AutoridadesContactadas>();
            BemAfectado = new HashSet<BemAfectado>();
            BemSalvado = new HashSet<BemSalvado>();
            CausadorSinistro = new HashSet<CausadorSinistro>();
            ConsequenciaSinistro = new HashSet<ConsequenciaSinistro>();
            DeclaracaoTestemunha = new HashSet<DeclaracaoTestemunha>();
            Excedente = new HashSet<Excedente>();
            FacultativoResseguro = new HashSet<FacultativoResseguro>();
            Fornecedor = new HashSet<Fornecedor>();
            IndeminizacaoNavigation = new HashSet<Indeminizacao>();
            Lesado = new HashSet<Lesado>();
            Medico = new HashSet<Medico>();
            Motorista = new HashSet<Motorista>();
            ObjectoEnvolvido = new HashSet<ObjectoEnvolvido>();
            OutrasInformacoesSinistro = new HashSet<OutrasInformacoesSinistro>();
            Paciente = new HashSet<Paciente>();
            PrejuizoSofridoVeiculoTerceiro = new HashSet<PrejuizoSofridoVeiculoTerceiro>();
            ReembolsoTratamentoDentario = new HashSet<ReembolsoTratamentoDentario>();
            RelatorioPolicia = new HashSet<RelatorioPolicia>();
            Responsabilizado = new HashSet<Responsabilizado>();
            Resseguro = new HashSet<Resseguro>();
            Sinistrado = new HashSet<Sinistrado>();
            SubFormaResseguroInformacao = new HashSet<SubFormaResseguroInformacao>();
            Terceiro = new HashSet<Terceiro>();
            Testemunha = new HashSet<Testemunha>();
        }

        [StringLength(50)]
        public string IdSinistro { get; set; }
        public long NumOrdemSinistro { get; set; }
        [Column("TipoSinistroID")]
        [StringLength(50)]
        public string TipoSinistroId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataOcorrencia { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataParticipacao { get; set; }
        public int? NumOcupantes { get; set; }
        public double? Indeminizacao { get; set; }
        [Column("ParticipanteSinistroID")]
        [StringLength(50)]
        public string ParticipanteSinistroId { get; set; }
        [Column("ClassificacaoParticipanteID")]
        [StringLength(50)]
        public string ClassificacaoParticipanteId { get; set; }
        [Column("IncidenteInspectorID")]
        [StringLength(50)]
        public string IncidenteInspectorId { get; set; }
        [Column("OBS")]
        [StringLength(2048)]
        public string Obs { get; set; }
        [StringLength(4000)]
        public string DescricaoSinistro { get; set; }
        public bool? Aprovado { get; set; }
        [Column("ApoliceID")]
        [StringLength(50)]
        public string ApoliceId { get; set; }
        [Column("EnderecoOcorrenciaID")]
        [StringLength(50)]
        public string EnderecoOcorrenciaId { get; set; }
        [StringLength(300)]
        public string CaminhoFicheiro { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        public bool Grave { get; set; }
        [Column("MoedaID")]
        [StringLength(50)]
        public string MoedaId { get; set; }
        [StringLength(50)]
        public string CodSinistro { get; set; }
        [StringLength(50)]
        public string ContaFinanceiraId { get; set; }
        public bool? OutroSeguroAbrangeEsteAcidente { get; set; }
        [StringLength(50)]
        public string EmQueSegurador { get; set; }
        [StringLength(50)]
        public string TipoSeguroId { get; set; }
        public bool? IncidenteRelacionanteAsuaProfissao { get; set; }
        public bool? SinistradoEraTransportadoEmVeiculo { get; set; }
        [StringLength(50)]
        public string ClassificacaoAutomovelId { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string MarcaAutomovelId { get; set; }
        [StringLength(50)]
        public string MatriculaVeiculo { get; set; }
        public bool? InteresseCondutor { get; set; }
        public bool? InteresseSegurado { get; set; }
        [StringLength(50)]
        public string Quilometragem { get; set; }
        public bool? IsPago { get; set; }

        [ForeignKey("ApoliceId")]
        [InverseProperty("Sinistro")]
        public virtual Apolice Apolice { get; set; }
        [ForeignKey("ClassificacaoAutomovelId")]
        [InverseProperty("Sinistro")]
        public virtual ClassificacaoAutomovel ClassificacaoAutomovel { get; set; }
        [ForeignKey("ClassificacaoParticipanteId")]
        [InverseProperty("Sinistro")]
        public virtual ClassificacaoParticipanteSinistro ClassificacaoParticipante { get; set; }
        [ForeignKey("ContaFinanceiraId")]
        [InverseProperty("Sinistro")]
        public virtual ContaFinanceira ContaFinanceira { get; set; }
        [ForeignKey("EnderecoOcorrenciaId")]
        [InverseProperty("Sinistro")]
        public virtual Endereco EnderecoOcorrencia { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Sinistro")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("IncidenteInspectorId")]
        [InverseProperty("SinistroIncidenteInspector")]
        public virtual Pessoa IncidenteInspector { get; set; }
        [ForeignKey("MarcaAutomovelId")]
        [InverseProperty("Sinistro")]
        public virtual MarcaAutomovel MarcaAutomovel { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("Sinistro")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("ParticipanteSinistroId")]
        [InverseProperty("SinistroParticipanteSinistro")]
        public virtual Pessoa ParticipanteSinistro { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("Sinistro")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("TipoSeguroId")]
        [InverseProperty("Sinistro")]
        public virtual TipoSeguro TipoSeguro { get; set; }
        [ForeignKey("TipoSinistroId")]
        [InverseProperty("Sinistro")]
        public virtual TipoSinistro TipoSinistro { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<AutoridadesContactadas> AutoridadesContactadas { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<BemAfectado> BemAfectado { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<BemSalvado> BemSalvado { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<CausadorSinistro> CausadorSinistro { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<ConsequenciaSinistro> ConsequenciaSinistro { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<DeclaracaoTestemunha> DeclaracaoTestemunha { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Excedente> Excedente { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<FacultativoResseguro> FacultativoResseguro { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Fornecedor> Fornecedor { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Indeminizacao> IndeminizacaoNavigation { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Lesado> Lesado { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Medico> Medico { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Motorista> Motorista { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<ObjectoEnvolvido> ObjectoEnvolvido { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<OutrasInformacoesSinistro> OutrasInformacoesSinistro { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Paciente> Paciente { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<PrejuizoSofridoVeiculoTerceiro> PrejuizoSofridoVeiculoTerceiro { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<ReembolsoTratamentoDentario> ReembolsoTratamentoDentario { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<RelatorioPolicia> RelatorioPolicia { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Responsabilizado> Responsabilizado { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Resseguro> Resseguro { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Sinistrado> Sinistrado { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<SubFormaResseguroInformacao> SubFormaResseguroInformacao { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Terceiro> Terceiro { get; set; }
        [InverseProperty("Sinistro")]
        public virtual ICollection<Testemunha> Testemunha { get; set; }
    }
}