// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class SobrePremioCoberturaAdicional
    {
        [StringLength(50)]
        public string IdSobrePremioCoberturaAdicional { get; set; }
        [StringLength(50)]
        public string CoberturaId { get; set; }
        [StringLength(50)]
        public string CodSobrePremioCoberturaAdicional { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        public double? PorCadaCapitalSeguro { get; set; }
        [StringLength(50)]
        public string CoberturaAdicionalId { get; set; }
        public double? SobrePremio { get; set; }

        [ForeignKey("CoberturaId")]
        [InverseProperty("SobrePremioCoberturaAdicionalCobertura")]
        public virtual Cobertura Cobertura { get; set; }
        [ForeignKey("CoberturaAdicionalId")]
        [InverseProperty("SobrePremioCoberturaAdicionalCoberturaAdicional")]
        public virtual Cobertura CoberturaAdicional { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("SobrePremioCoberturaAdicional")]
        public virtual Estado Estado { get; set; }
    }
}