// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class SubRisco
    {
        [StringLength(50)]
        public string IdSubRisco { get; set; }
        [StringLength(300)]
        public string Designacao { get; set; }
        [Column("RiscoID")]
        [StringLength(50)]
        public string RiscoId { get; set; }
        [StringLength(10)]
        public string CodSubRisco { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("SubRisco")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("RiscoId")]
        [InverseProperty("SubRisco")]
        public virtual Risco Risco { get; set; }
    }
}