// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Sugestao
    {
        [StringLength(50)]
        public string IdSugestao { get; set; }
        [StringLength(2048)]
        public string Designacao { get; set; }
        [Column("PessoaID")]
        [StringLength(50)]
        public string PessoaId { get; set; }
        [Column("TipoSugestaoID")]
        [StringLength(50)]
        public string TipoSugestaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataHora { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [StringLength(50)]
        public string CodSugestao { get; set; }
        [StringLength(300)]
        public string Assunto { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("Sugestao")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("Sugestao")]
        public virtual Pessoa Pessoa { get; set; }
        [ForeignKey("TipoSugestaoId")]
        [InverseProperty("Sugestao")]
        public virtual TipoSugestao TipoSugestao { get; set; }
    }
}