// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    [Table("SYS_Auditoria")]
    public partial class SysAuditoria
    {
        public long IdAuditoria { get; set; }
        [Required]
        [Column("Audit_IdUser")]
        [StringLength(50)]
        public string AuditIdUser { get; set; }
        [Required]
        [Column("Audit_Tabela")]
        [StringLength(100)]
        public string AuditTabela { get; set; }
        [Required]
        [Column("Audt_TipoOperacao")]
        [StringLength(50)]
        public string AudtTipoOperacao { get; set; }
        [Required]
        [Column("Audit_IdRegisto")]
        [StringLength(50)]
        public string AuditIdRegisto { get; set; }
        [Column("Audit_Data_Time", TypeName = "datetime")]
        public DateTime AuditDataTime { get; set; }
        [Required]
        [Column("Audit_MacAddres")]
        [StringLength(100)]
        public string AuditMacAddres { get; set; }
        [Required]
        [Column("Audit_IP")]
        [StringLength(15)]
        public string AuditIp { get; set; }
        [Required]
        [Column("Audit_SO")]
        [StringLength(50)]
        public string AuditSo { get; set; }
        [Column("Audit_Região")]
        [StringLength(50)]
        public string AuditRegião { get; set; }
        [Column("Audit_Pais")]
        [StringLength(50)]
        public string AuditPais { get; set; }
        [Column("Audit_Provicia")]
        [StringLength(50)]
        public string AuditProvicia { get; set; }
        [Column("Audit_Modulo")]
        [StringLength(100)]
        public string AuditModulo { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("SysAuditoria")]
        public virtual Estado Estado { get; set; }
    }
}