// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TabuaAngv2020P
    {
        [StringLength(50)]
        public string IdTabua { get; set; }
        public byte? Idade { get; set; }
        [Column("M_x")]
        public double? MX { get; set; }
        [Column("Q_x")]
        public double? QX { get; set; }
        [Column("D_x")]
        public double? DX { get; set; }
        [Column("P_x")]
        public double? PX { get; set; }
        [Column("I_x")]
        public double? IX { get; set; }
        [Column("L_x")]
        public double? LX { get; set; }
        [Column("T_x")]
        public double? TX { get; set; }
        [Column("E_x")]
        public double? EX { get; set; }
        [Column("U_x")]
        public double? UX { get; set; }
        [StringLength(10)]
        public string CodTabuaAngv2020P { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TabuaAngv2020P")]
        public virtual Estado Estado { get; set; }
    }
}