// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Tarefa
    {
        public Tarefa()
        {
            PessoaTarefa = new HashSet<PessoaTarefa>();
            SubTarefa = new HashSet<SubTarefa>();
            SubscricaoCessaoRetencao = new HashSet<SubscricaoCessaoRetencao>();
            TarefaPlano = new HashSet<TarefaPlano>();
            TarefasActividade = new HashSet<TarefasActividade>();
        }

        [StringLength(50)]
        public string IdTarefa { get; set; }
        [Column("PCFid")]
        [StringLength(20)]
        public string Pcfid { get; set; }
        [Column("HierarquiaID")]
        [StringLength(20)]
        public string HierarquiaId { get; set; }
        [StringLength(300)]
        public string Nome { get; set; }
        [StringLength(2)]
        public string MetricaDisponivel { get; set; }
        public int? IndiceDiferenca { get; set; }
        [StringLength(100)]
        public string DetalhesMudanca { get; set; }
        [StringLength(10)]
        public string CodTarefa { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("DireccaoID")]
        [StringLength(50)]
        public string DireccaoId { get; set; }
        [Column("NivelRiscoID")]
        [StringLength(50)]
        public string NivelRiscoId { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("PrioridadeID")]
        [StringLength(50)]
        public string PrioridadeId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }

        [ForeignKey("DireccaoId")]
        [InverseProperty("Tarefa")]
        public virtual Direccao Direccao { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Tarefa")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("NivelRiscoId")]
        [InverseProperty("Tarefa")]
        public virtual NivelRisco NivelRisco { get; set; }
        [ForeignKey("PrioridadeId")]
        [InverseProperty("Tarefa")]
        public virtual Prioridade Prioridade { get; set; }
        [InverseProperty("Tarefa")]
        public virtual ICollection<PessoaTarefa> PessoaTarefa { get; set; }
        [InverseProperty("Tarefa")]
        public virtual ICollection<SubTarefa> SubTarefa { get; set; }
        [InverseProperty("Tarefa")]
        public virtual ICollection<SubscricaoCessaoRetencao> SubscricaoCessaoRetencao { get; set; }
        [InverseProperty("Tarefa")]
        public virtual ICollection<TarefaPlano> TarefaPlano { get; set; }
        [InverseProperty("Tarefa")]
        public virtual ICollection<TarefasActividade> TarefasActividade { get; set; }
    }
}