// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TarefaReparacao
    {
        [StringLength(50)]
        public string IdTarefaReparacao { get; set; }
        [StringLength(1000)]
        public string Designacao { get; set; }
        public bool? AutorizadaPorEngenheiro { get; set; }
        public bool? AutorizadoPeloDono { get; set; }
        [Column("CategoriaLaboralID")]
        [StringLength(50)]
        public string CategoriaLaboralId { get; set; }
        [Column("TipoTarefaReparacaoID")]
        [StringLength(50)]
        public string TipoTarefaReparacaoId { get; set; }
        [Column("ReparacaoID")]
        [StringLength(50)]
        public string ReparacaoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("CategoriaLaboralId")]
        [InverseProperty("TarefaReparacao")]
        public virtual CategoriaLaboral CategoriaLaboral { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("TarefaReparacao")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("ReparacaoId")]
        [InverseProperty("TarefaReparacao")]
        public virtual Reparacao Reparacao { get; set; }
        [ForeignKey("TipoTarefaReparacaoId")]
        [InverseProperty("TarefaReparacao")]
        public virtual TipoTarefaReparacao TipoTarefaReparacao { get; set; }
    }
}