// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    [Table("TarifasPremioAutoAT2")]
    public partial class TarifasPremioAutoAt2
    {
        [StringLength(50)]
        public string IdTarifa { get; set; }
        public int? Classe { get; set; }
        public int? SubClasse { get; set; }
        [StringLength(500)]
        public string Descricao { get; set; }
        public double Taxa { get; set; }
        [Column("SubContaID")]
        [StringLength(50)]
        public string SubContaId { get; set; }
        [Column("ProdutoID")]
        [StringLength(50)]
        public string ProdutoId { get; set; }
        [Column("CodTarifasPremioAutoAT2")]
        [StringLength(10)]
        public string CodTarifasPremioAutoAt2 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("LinhaProdutoID")]
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }
        [Required]
        public bool? IsTaxa { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string NaturezaMovimentoId { get; set; }
        [Required]
        public bool? Contabiliza { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TarifasPremioAutoAt2")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("TarifasPremioAutoAt2")]
        public virtual LinhaProduto LinhaProduto { get; set; }
        [ForeignKey("NaturezaMovimentoId")]
        [InverseProperty("TarifasPremioAutoAt2")]
        public virtual NaturezaMovimento NaturezaMovimento { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("TarifasPremioAutoAt2")]
        public virtual Produto Produto { get; set; }
        [ForeignKey("SubContaId")]
        [InverseProperty("TarifasPremioAutoAt2")]
        public virtual PlanoContas SubConta { get; set; }
    }
}