// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Tarifa
    {
        public Tarifa()
        {
            Agravamento = new HashSet<Agravamento>();
            CondicaoTarifa = new HashSet<CondicaoTarifa>();
        }

        [StringLength(50)]
        public string IdTarifa { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string TipoTarifaId { get; set; }
        [StringLength(50)]
        public string ClasseRiscoId { get; set; }
        [StringLength(50)]
        public string CanalId { get; set; }
        [StringLength(50)]
        public string CentroCustoId { get; set; }
        [StringLength(50)]
        public string SubContaId { get; set; }
        [StringLength(50)]
        public string TipoRecebimentoId { get; set; }
        [StringLength(50)]
        public string PapelId { get; set; }
        [StringLength(50)]
        public string ProdutoId { get; set; }
        public bool? IsPadrao { get; set; }
        [StringLength(50)]
        public string PlanoProdutoId { get; set; }
        [StringLength(50)]
        public string LinhaProdutoId { get; set; }

        [ForeignKey("CanalId")]
        [InverseProperty("Tarifa")]
        public virtual Canal Canal { get; set; }
        [ForeignKey("CentroCustoId")]
        [InverseProperty("Tarifa")]
        public virtual CentroCusto CentroCusto { get; set; }
        [ForeignKey("ClasseRiscoId")]
        [InverseProperty("Tarifa")]
        public virtual ClasseRisco ClasseRisco { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Tarifa")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LinhaProdutoId")]
        [InverseProperty("Tarifa")]
        public virtual LinhaProduto LinhaProduto { get; set; }
        [ForeignKey("PapelId")]
        [InverseProperty("Tarifa")]
        public virtual Papel Papel { get; set; }
        [ForeignKey("PlanoProdutoId")]
        [InverseProperty("Tarifa")]
        public virtual PlanoProduto PlanoProduto { get; set; }
        [ForeignKey("ProdutoId")]
        [InverseProperty("Tarifa")]
        public virtual Produto Produto { get; set; }
        [ForeignKey("SubContaId")]
        [InverseProperty("Tarifa")]
        public virtual PlanoContas SubConta { get; set; }
        [ForeignKey("TipoRecebimentoId")]
        [InverseProperty("Tarifa")]
        public virtual TipoRecebimento TipoRecebimento { get; set; }
        [ForeignKey("TipoTarifaId")]
        [InverseProperty("Tarifa")]
        public virtual TipoTarifa TipoTarifa { get; set; }
        [InverseProperty("Tarifa")]
        public virtual ICollection<Agravamento> Agravamento { get; set; }
        [InverseProperty("Tarifa")]
        public virtual ICollection<CondicaoTarifa> CondicaoTarifa { get; set; }
    }
}