// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Terceiro
    {
        [StringLength(50)]
        public string IdTerceiro { get; set; }
        [Column("TipoRelacaoSeguradoID")]
        [StringLength(50)]
        public string TipoRelacaoSeguradoId { get; set; }
        [Column("PessoaID")]
        [StringLength(50)]
        public string PessoaId { get; set; }
        [StringLength(50)]
        public string SinistroId { get; set; }
        public double? ValorEstimado { get; set; }
        [Column("MoedaID")]
        [StringLength(50)]
        public string MoedaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [StringLength(50)]
        public string CodTerceiro { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("Terceiro")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MoedaId")]
        [InverseProperty("Terceiro")]
        public virtual Moeda Moeda { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("Terceiro")]
        public virtual Pessoa Pessoa { get; set; }
        [ForeignKey("SinistroId")]
        [InverseProperty("Terceiro")]
        public virtual Sinistro Sinistro { get; set; }
        [ForeignKey("TipoRelacaoSeguradoId")]
        [InverseProperty("Terceiro")]
        public virtual TipoRelacaoSegurado TipoRelacaoSegurado { get; set; }
    }
}