// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoRisco
    {
        public TipoRisco()
        {
            Risco = new HashSet<Risco>();
        }

        [StringLength(50)]
        public string IdTipoRisco { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string CodTipoRisco { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoRisco")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoRisco")]
        public virtual ICollection<Risco> Risco { get; set; }
    }
}