// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoSanguineo
    {
        public TipoSanguineo()
        {
            Pessoa = new HashSet<Pessoa>();
        }

        [StringLength(50)]
        public string IdTipoSanguineo { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string CodTipoSanguineo { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoSanguineo")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoSanguineo")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}