// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoEncargo
    {
        public TipoEncargo()
        {
            Encargos = new HashSet<Encargos>();
        }

        [StringLength(50)]
        public string IdTipoEncargo { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [Column("NaturezaMovimentoID")]
        [StringLength(50)]
        public string NaturezaMovimentoId { get; set; }
        [StringLength(10)]
        public string CodTipoEncargo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(500)]
        public string CaminhoIcone { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [Required]
        public bool? Contabiliza { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoEncargo")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoEncargo")]
        public virtual ICollection<Encargos> Encargos { get; set; }
    }
}