// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoDocumentos
    {
        public TipoDocumentos()
        {
            Comissao = new HashSet<Comissao>();
            Cotacao = new HashSet<Cotacao>();
            ImpostoTipoDocumentos = new HashSet<ImpostoTipoDocumentos>();
            Movimento = new HashSet<Movimento>();
            TipoOperacao = new HashSet<TipoOperacao>();
        }

        [StringLength(50)]
        public string IdTipoDocumentos { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [Required]
        [StringLength(10)]
        public string CodTipoDocumentos { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(500)]
        public string CaminhoIcone { get; set; }
        [StringLength(200)]
        public string HistoricoMovimento { get; set; }
        [Required]
        public bool? Antecede { get; set; }
        [StringLength(50)]
        public string CodigoAgtTipoDocumento { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoDocumentos")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoDocumento")]
        public virtual ICollection<Comissao> Comissao { get; set; }
        [InverseProperty("TipoDocumento")]
        public virtual ICollection<Cotacao> Cotacao { get; set; }
        [InverseProperty("TipoDocumentos")]
        public virtual ICollection<ImpostoTipoDocumentos> ImpostoTipoDocumentos { get; set; }
        public virtual ICollection<Movimento> Movimento { get; set; }
        [InverseProperty("TipoDocumento")]
        public virtual ICollection<TipoOperacao> TipoOperacao { get; set; }
    }
}