// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoJustificativoCativo
    {
        public TipoJustificativoCativo()
        {
            ValorCativo = new HashSet<ValorCativo>();
        }

        [StringLength(50)]
        public string IdTipoJustificativo { get; set; }
        [StringLength(50)]
        public string CodTipoJustificativo { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoJustificativoCativo")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoJustificativoCativo")]
        public virtual ICollection<ValorCativo> ValorCativo { get; set; }
    }
}