// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoEmbarcacao
    {
        [StringLength(50)]
        public string IdTipoEmbarcacao { get; set; }
        [StringLength(50)]
        public string CodTipoEmbarcacao { get; set; }
        [StringLength(200)]
        public string Designacao { get; set; }
        [StringLength(200)]
        public string Criterio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoEmbarcacao")]
        public virtual Estado Estado { get; set; }
    }
}