// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoAdesao
    {
        public TipoAdesao()
        {
            CoeficientePremioAdesao = new HashSet<CoeficientePremioAdesao>();
        }

        [StringLength(50)]
        public string IdTipoAdesao { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string CodTipoAdesao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("FormaContratacaoID")]
        [StringLength(50)]
        public string FormaContratacaoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoAdesao")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("FormaContratacaoId")]
        [InverseProperty("TipoAdesao")]
        public virtual FormaContratacao FormaContratacao { get; set; }
        [InverseProperty("TipoAdesao")]
        public virtual ICollection<CoeficientePremioAdesao> CoeficientePremioAdesao { get; set; }
    }
}