// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoConta
    {
        public TipoConta()
        {
            Cliente = new HashSet<Cliente>();
            ContaFinanceira = new HashSet<ContaFinanceira>();
            DescontoTipoConta = new HashSet<DescontoTipoConta>();
            DespesasTipoConta = new HashSet<DespesasTipoConta>();
            EncargosTipoConta = new HashSet<EncargosTipoConta>();
            ImpostoTipoConta = new HashSet<ImpostoTipoConta>();
            SubTipoConta = new HashSet<SubTipoConta>();
            ValorCativo = new HashSet<ValorCativo>();
        }

        [StringLength(50)]
        public string IdTipoConta { get; set; }
        [StringLength(50)]
        public string CodTipoConta { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string NaturezaMovimentoId { get; set; }
        [StringLength(50)]
        public string SubContaId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [StringLength(50)]
        public string LinhProdutoId { get; set; }
        [StringLength(50)]
        public string PapelId { get; set; }
        [StringLength(50)]
        public string SubTipoContaId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoConta")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LinhProdutoId")]
        [InverseProperty("TipoConta")]
        public virtual LinhaProduto LinhProduto { get; set; }
        [ForeignKey("NaturezaMovimentoId")]
        [InverseProperty("TipoConta")]
        public virtual NaturezaMovimento NaturezaMovimento { get; set; }
        [ForeignKey("PapelId")]
        [InverseProperty("TipoConta")]
        public virtual Papel Papel { get; set; }
        [ForeignKey("SubContaId")]
        [InverseProperty("TipoConta")]
        public virtual PlanoContas SubConta { get; set; }
        [ForeignKey("SubTipoContaId")]
        [InverseProperty("TipoContaNavigation")]
        public virtual SubTipoConta SubTipoContaNavigation { get; set; }
        [InverseProperty("TipoConta")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [InverseProperty("TipoConta")]
        public virtual ICollection<ContaFinanceira> ContaFinanceira { get; set; }
        [InverseProperty("TipoConta")]
        public virtual ICollection<DescontoTipoConta> DescontoTipoConta { get; set; }
        [InverseProperty("TipoConta")]
        public virtual ICollection<DespesasTipoConta> DespesasTipoConta { get; set; }
        [InverseProperty("TipoConta")]
        public virtual ICollection<EncargosTipoConta> EncargosTipoConta { get; set; }
        [InverseProperty("TipoConta")]
        public virtual ICollection<ImpostoTipoConta> ImpostoTipoConta { get; set; }
        [InverseProperty("TipoConta")]
        public virtual ICollection<SubTipoConta> SubTipoConta { get; set; }
        [InverseProperty("TipoConta")]
        public virtual ICollection<ValorCativo> ValorCativo { get; set; }
    }
}