// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoMatricula
    {
        public TipoMatricula()
        {
            Automovel = new HashSet<Automovel>();
        }

        [StringLength(50)]
        public string IdTipoMatricula { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string CodTipoMatricula { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoMatricula")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoMatricula")]
        public virtual ICollection<Automovel> Automovel { get; set; }
    }
}