// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoFacturamento
    {
        public TipoFacturamento()
        {
            Canal = new HashSet<Canal>();
        }

        [StringLength(50)]
        public string IdTipoFacturamento { get; set; }
        [StringLength(10)]
        public string CodTipoFacturamento { get; set; }
        [StringLength(200)]
        public string Designacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoFacturamento")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoFacturamento")]
        public virtual ICollection<Canal> Canal { get; set; }
    }
}