// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoOperacaoProcessoLimiteCompetencia
    {
        [StringLength(50)]
        public string IdTipoOperacaoProcessoLimiteCompetencia { get; set; }
        [StringLength(50)]
        public string LimiteCompetenciaId { get; set; }
        [StringLength(50)]
        public string CodTipoOperacaoProcessoLimiteCompetencia { get; set; }
        [StringLength(50)]
        public string TipoOperacaoProcessoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoOperacaoProcessoLimiteCompetencia")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("LimiteCompetenciaId")]
        [InverseProperty("TipoOperacaoProcessoLimiteCompetencia")]
        public virtual LimiteCompetencia LimiteCompetencia { get; set; }
        [ForeignKey("TipoOperacaoProcessoId")]
        [InverseProperty("TipoOperacaoProcessoLimiteCompetencia")]
        public virtual TipoOperacaoProcesso TipoOperacaoProcesso { get; set; }
    }
}