// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoInstalacoes
    {
        public TipoInstalacoes()
        {
            LocalizacaoInstalacoes = new HashSet<LocalizacaoInstalacoes>();
        }

        [StringLength(50)]
        public string IdTipoInstalacao { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodTipoInstalacoes { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(500)]
        public string CaminhoIcone { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoInstalacoes")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoInstalacoes")]
        public virtual ICollection<LocalizacaoInstalacoes> LocalizacaoInstalacoes { get; set; }
    }
}