// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoTarefaReparacao
    {
        public TipoTarefaReparacao()
        {
            TarefaReparacao = new HashSet<TarefaReparacao>();
        }

        [StringLength(50)]
        public string IdTipoTarefaReparacao { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodTipoTarefaReparacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(500)]
        public string CaminhoIcone { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoTarefaReparacao")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoTarefaReparacao")]
        public virtual ICollection<TarefaReparacao> TarefaReparacao { get; set; }
    }
}