// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoLevantamentoMedicamento
    {
        public TipoLevantamentoMedicamento()
        {
            DescontoFranquiaMedicamento = new HashSet<DescontoFranquiaMedicamento>();
        }

        [StringLength(50)]
        public string IdTipoLevantamentoMedicamento { get; set; }
        [StringLength(200)]
        public string Designacao { get; set; }
        [StringLength(50)]
        public string CodTipoLevantamentoMedicamento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataActualizacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoLevantamentoMedicamento")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoLevantamentoMedicamento")]
        public virtual ICollection<DescontoFranquiaMedicamento> DescontoFranquiaMedicamento { get; set; }
    }
}