// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoImposto
    {
        public TipoImposto()
        {
            Imposto = new HashSet<Imposto>();
            PeriodoAnualImposto = new HashSet<PeriodoAnualImposto>();
        }

        [StringLength(50)]
        public string IdTipoImposto { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodTipoImposto { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(500)]
        public string CaminhoIcone { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [Required]
        public bool? Contabiliza { get; set; }
        [StringLength(50)]
        public string ClassificacaoImpostoId { get; set; }
        [StringLength(50)]
        public string TipoRamoSeguroId { get; set; }

        [ForeignKey("ClassificacaoImpostoId")]
        [InverseProperty("TipoImposto")]
        public virtual ClassificacaoImposto ClassificacaoImposto { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("TipoImposto")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("TipoRamoSeguroId")]
        [InverseProperty("TipoImposto")]
        public virtual TipoRamoSeguro TipoRamoSeguro { get; set; }
        [InverseProperty("TipoImposto")]
        public virtual ICollection<Imposto> Imposto { get; set; }
        [InverseProperty("TipoImposto")]
        public virtual ICollection<PeriodoAnualImposto> PeriodoAnualImposto { get; set; }
    }
}