// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoPagamento
    {
        public TipoPagamento()
        {
            Contrato = new HashSet<Contrato>();
            ContratoPrestadorEmpresa = new HashSet<ContratoPrestadorEmpresa>();
            SubTipoPagamento = new HashSet<SubTipoPagamento>();
        }

        [StringLength(50)]
        public string IdTipoPagamento { get; set; }
        [StringLength(800)]
        public string Designacao { get; set; }
        [Required]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataActualizacao { get; set; }
        [StringLength(50)]
        public string CodTipoPagamento { get; set; }
        public int? CodigoTipoPagamento { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoPagamento")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoPagamento")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [InverseProperty("TipoPagamento")]
        public virtual ICollection<ContratoPrestadorEmpresa> ContratoPrestadorEmpresa { get; set; }
        [InverseProperty("TipoPagamento")]
        public virtual ICollection<SubTipoPagamento> SubTipoPagamento { get; set; }
    }
}