// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TiposContratosResseguroInformacoesTiposContratosResseguro
    {
        [StringLength(50)]
        public string IdTiposContratosResseguroInformacoesTiposContratosResseguro { get; set; }
        [StringLength(50)]
        public string TiposContratosResseguroId { get; set; }
        [StringLength(50)]
        public string InformacoesTiposContratosResseguroId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(10)]
        public string CodTiposContratosResseguroInformacoesTiposContratosResseguro { get; set; }

        [ForeignKey("InformacoesTiposContratosResseguroId")]
        [InverseProperty("TiposContratosResseguroInformacoesTiposContratosResseguro")]
        public virtual SubFormaResseguroInformacao InformacoesTiposContratosResseguro { get; set; }
        [ForeignKey("TiposContratosResseguroId")]
        [InverseProperty("TiposContratosResseguroInformacoesTiposContratosResseguro")]
        public virtual TiposContratosResseguro TiposContratosResseguro { get; set; }
    }
}