// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoRamoSeguro
    {
        public TipoRamoSeguro()
        {
            Imposto = new HashSet<Imposto>();
            OutraSeguradoraContrato = new HashSet<OutraSeguradoraContrato>();
            PortfolioProduto = new HashSet<PortfolioProduto>();
            RamoQualidadeSegura = new HashSet<RamoQualidadeSegura>();
            RapelProdutor = new HashSet<RapelProdutor>();
            ReservasTecnicas = new HashSet<ReservasTecnicas>();
            TipoDesvalorizacao = new HashSet<TipoDesvalorizacao>();
            TipoImposto = new HashSet<TipoImposto>();
        }

        [StringLength(50)]
        public string IdTipo { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodTipoRamoSeguro { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(500)]
        public string CaminhoIcone { get; set; }
        public double? Taxa { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoRamoSeguro")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoRamoSeguro")]
        public virtual ICollection<Imposto> Imposto { get; set; }
        [InverseProperty("TipoRamoSeguro")]
        public virtual ICollection<OutraSeguradoraContrato> OutraSeguradoraContrato { get; set; }
        [InverseProperty("TipoRamoSeguro")]
        public virtual ICollection<PortfolioProduto> PortfolioProduto { get; set; }
        [InverseProperty("RamoSeguro")]
        public virtual ICollection<RamoQualidadeSegura> RamoQualidadeSegura { get; set; }
        [InverseProperty("TipoRamo")]
        public virtual ICollection<RapelProdutor> RapelProdutor { get; set; }
        [InverseProperty("TipoRamoSeguro")]
        public virtual ICollection<ReservasTecnicas> ReservasTecnicas { get; set; }
        [InverseProperty("TipoRamoSeguro")]
        public virtual ICollection<TipoDesvalorizacao> TipoDesvalorizacao { get; set; }
        [InverseProperty("TipoRamoSeguro")]
        public virtual ICollection<TipoImposto> TipoImposto { get; set; }
    }
}