// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoCosseguro
    {
        public TipoCosseguro()
        {
            CoSeguro = new HashSet<CoSeguro>();
        }

        [StringLength(50)]
        public string IdTipoCosseguro { get; set; }
        [StringLength(100)]
        public string Designacao { get; set; }
        [StringLength(10)]
        public string CodTipoCosseguro { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(500)]
        public string CaminhoIcone { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("TipoCosseguro")]
        public virtual Estado Estado { get; set; }
        [InverseProperty("TipoCosseguro")]
        public virtual ICollection<CoSeguro> CoSeguro { get; set; }
    }
}