// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TipoComissionamentoResseguro
    {
        [StringLength(50)]
        public string IdTipoComissionamentoResseguro { get; set; }
        [StringLength(50)]
        public string ComissionamentoId { get; set; }
        [StringLength(50)]
        public string CodTipoComissionamentoResseguro { get; set; }
        [StringLength(50)]
        public string ContratoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }
        [StringLength(50)]
        public string Designacao { get; set; }

        [ForeignKey("ComissionamentoId")]
        [InverseProperty("TipoComissionamentoResseguro")]
        public virtual Comissionamento Comissionamento { get; set; }
        [ForeignKey("ContratoId")]
        [InverseProperty("TipoComissionamentoResseguro")]
        public virtual Contrato Contrato { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("TipoComissionamentoResseguro")]
        public virtual Estado Estado { get; set; }
    }
}