// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Titularidade
    {
        [StringLength(50)]
        public string IdTitularidade { get; set; }
        [StringLength(50)]
        public string PessoaId { get; set; }
        public bool? Principal { get; set; }
        [StringLength(50)]
        public string ContaFinanceiraId { get; set; }

        [ForeignKey("ContaFinanceiraId")]
        [InverseProperty("Titularidade")]
        public virtual ContaFinanceira ContaFinanceira { get; set; }
        [ForeignKey("PessoaId")]
        [InverseProperty("Titularidade")]
        public virtual Pessoa Pessoa { get; set; }
    }
}