// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class TransferenciaSeguro
    {
        [StringLength(50)]
        public string IdTransferenciaSeguro { get; set; }
        public bool? JaEsteveSeguroParaEsteMesmoRisco { get; set; }
        [StringLength(50)]
        public string QualSeguradora { get; set; }
        [StringLength(50)]
        public string CodTransferenciaSeguro { get; set; }
        [StringLength(500)]
        public string RazaoAnulacao { get; set; }
        public bool? TemDebitos { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
    }
}