// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ValorPadrao
    {
        [StringLength(50)]
        public string IdValorCaracteristica { get; set; }
        [StringLength(50)]
        public string CaracteristicaId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [StringLength(50)]
        public string UnidadeId { get; set; }
        [StringLength(50)]
        public string Valor { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("CaracteristicaId")]
        [InverseProperty("ValorPadrao")]
        public virtual CaracteristicaClassificacao Caracteristica { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("ValorPadrao")]
        public virtual Estado Estado { get; set; }
    }
}