// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class ValoresTipoAntena
    {
        public ValoresTipoAntena()
        {
            ModalidadesRcselecionadas = new HashSet<ModalidadesRcselecionadas>();
        }

        [StringLength(50)]
        public string IdValorTipoAntena { get; set; }
        public double? ValorMax { get; set; }
        [Column("TipoAntenaID")]
        [StringLength(50)]
        public string TipoAntenaId { get; set; }
        [StringLength(10)]
        public string CodValoresTipoAntena { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }

        [ForeignKey("EstadoId")]
        [InverseProperty("ValoresTipoAntena")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("TipoAntenaId")]
        [InverseProperty("ValoresTipoAntena")]
        public virtual LocalidadeAntena TipoAntena { get; set; }
        [InverseProperty("ValorTipoAntena")]
        public virtual ICollection<ModalidadesRcselecionadas> ModalidadesRcselecionadas { get; set; }
    }
}