// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ISS.Application.Models
{
    public partial class Viagem
    {
        [StringLength(50)]
        public string IdDadosViagem { get; set; }
        [Column("PaisOrigemID")]
        [StringLength(50)]
        public string PaisOrigemId { get; set; }
        [Column("PaisDestinoID")]
        [StringLength(50)]
        public string PaisDestinoId { get; set; }
        [Column("MeioTransporteID")]
        [StringLength(50)]
        public string MeioTransporteId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataCompraBilhete { get; set; }
        [Column("CompanhiaViagemID")]
        [StringLength(50)]
        public string CompanhiaViagemId { get; set; }
        [Column("CotacaoID")]
        [StringLength(50)]
        public string CotacaoId { get; set; }
        [Column("PeriodoPlanoID")]
        [StringLength(50)]
        public string PeriodoPlanoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        [Column("ApoliceID")]
        [StringLength(50)]
        public string ApoliceId { get; set; }
        [Column("EstadoID")]
        [StringLength(50)]
        public string EstadoId { get; set; }
        [Column("UltModificacaoPorID")]
        [StringLength(50)]
        public string UltModificacaoPorId { get; set; }
        [StringLength(50)]
        public string ProvinciaOrigemId { get; set; }
        [StringLength(50)]
        public string ProvinciaDestinoId { get; set; }

        [ForeignKey("CompanhiaViagemId")]
        [InverseProperty("Viagem")]
        public virtual CompanhiaViagem CompanhiaViagem { get; set; }
        [ForeignKey("CotacaoId")]
        [InverseProperty("Viagem")]
        public virtual Cotacao Cotacao { get; set; }
        [ForeignKey("EstadoId")]
        [InverseProperty("Viagem")]
        public virtual Estado Estado { get; set; }
        [ForeignKey("MeioTransporteId")]
        [InverseProperty("Viagem")]
        public virtual MeioTransporte MeioTransporte { get; set; }
        [ForeignKey("PaisDestinoId")]
        [InverseProperty("ViagemPaisDestino")]
        public virtual Pais PaisDestino { get; set; }
        [ForeignKey("PaisOrigemId")]
        [InverseProperty("ViagemPaisOrigem")]
        public virtual Pais PaisOrigem { get; set; }
        [ForeignKey("PeriodoPlanoId")]
        [InverseProperty("Viagem")]
        public virtual PeriodoPlano PeriodoPlano { get; set; }
        [ForeignKey("ProvinciaDestinoId")]
        [InverseProperty("ViagemProvinciaDestino")]
        public virtual Provincia ProvinciaDestino { get; set; }
        [ForeignKey("ProvinciaOrigemId")]
        [InverseProperty("ViagemProvinciaOrigem")]
        public virtual Provincia ProvinciaOrigem { get; set; }
    }
}